# 🎓 Complete NumPy Tutorial: From Zero to Hero

## Welcome! 👋

Think of NumPy as a super-powered calculator for Python. Just like how a calculator helps you do math faster, NumPy helps Python work with numbers REALLY fast!

**What you'll learn:**
- How to create and use arrays (like super lists!)
- How to do math on lots of numbers at once
- Cool tricks to manipulate data
- Real-world examples you can use

Let's get started! 🚀

In [1]:
# First, let's import NumPy
# Think of 'import' like opening a toolbox - we're getting our NumPy tools ready!
# We use 'np' as a nickname for numpy (shorter to type!)
import numpy as np

# Let's check which version we have
print(f"NumPy version: {np.__version__}")
print("\n✅ NumPy is ready to use!")

NumPy version: 1.25.0

✅ NumPy is ready to use!


---
# 📦 Part 1: Creating Arrays (The Basics)

## What is an Array?

Imagine you have a box of toys. A Python list is like that box - you can put different toys in it.
A NumPy array is like a **special organized box** where:
- All toys must be the same type (all cars, or all blocks)
- They're arranged in a neat grid
- You can do math on ALL toys at once!

Let's create some arrays!

In [2]:
# Creating a 1D array (like a single row of numbers)
# Think of this as a line of students standing in a row
my_first_array = np.array([1, 2, 3, 4, 5])

print("My first array:")
print(my_first_array)
print("\nThis is like having 5 students in a line: 1, 2, 3, 4, 5")

My first array:
[1 2 3 4 5]

This is like having 5 students in a line: 1, 2, 3, 4, 5


In [3]:
# Creating a 2D array (like a table or grid)
# Think of this as students sitting in rows and columns (like a classroom!)
my_2d_array = np.array([
    [1, 2, 3],    # First row (3 students)
    [4, 5, 6],    # Second row (3 students)
    [7, 8, 9]     # Third row (3 students)
])

print("My 2D array (like a classroom):")
print(my_2d_array)
print("\n📊 This is like a 3x3 grid - 3 rows and 3 columns!")

My 2D array (like a classroom):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

📊 This is like a 3x3 grid - 3 rows and 3 columns!


In [4]:
# Creating a 3D array (like stacking multiple grids)
# Think of this as multiple classrooms stacked on top of each other!
my_3d_array = np.array([
    [[1, 2], [3, 4]],      # First classroom
    [[5, 6], [7, 8]]       # Second classroom
])

print("My 3D array (like multiple classrooms):")
print(my_3d_array)
print("\n🏢 This is like having 2 floors, each with a 2x2 grid!")

My 3D array (like multiple classrooms):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

🏢 This is like having 2 floors, each with a 2x2 grid!


## 🎨 Special Ways to Create Arrays

NumPy has shortcuts to create arrays without typing every number!

In [5]:
# Creating an array full of zeros
# Like having empty boxes - all contain 0
zeros_array = np.zeros((3, 4))  # 3 rows, 4 columns

print("Array full of zeros (empty boxes):")
print(zeros_array)
print("\n💡 Useful when you want to start with empty values!")

Array full of zeros (empty boxes):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

💡 Useful when you want to start with empty values!


In [6]:
# Creating an array full of ones
# Like having boxes with 1 item each
ones_array = np.ones((2, 5))  # 2 rows, 5 columns

print("Array full of ones:")
print(ones_array)
print("\n💡 Useful when you want to start with 1s!")

Array full of ones:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

💡 Useful when you want to start with 1s!


In [7]:
# Creating an array with a specific number repeated
# Like filling all boxes with the same number
full_array = np.full((3, 3), 7)  # 3x3 grid, all filled with 7

print("Array full of 7s:")
print(full_array)
print("\n💡 Every box has the number 7!")

Array full of 7s:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

💡 Every box has the number 7!


In [8]:
# Creating an identity matrix (special diagonal pattern)
# Like a checkerboard where only the diagonal has 1s
identity = np.eye(4)  # 4x4 identity matrix

print("Identity matrix (1s on diagonal):")
print(identity)
print("\n💡 Notice the diagonal line of 1s? Very useful in math!")

Identity matrix (1s on diagonal):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

💡 Notice the diagonal line of 1s? Very useful in math!


## 🔢 Creating Number Sequences

Sometimes you want numbers in order, like counting!

In [9]:
# Using arange (like Python's range, but for arrays)
# Think of this as counting: start, stop, step

# Count from 0 to 9
count_to_10 = np.arange(10)
print("Count 0 to 9:")
print(count_to_10)

# Count from 5 to 14
count_5_to_15 = np.arange(5, 15)
print("\nCount 5 to 14:")
print(count_5_to_15)

# Count by 2s (even numbers)
even_numbers = np.arange(0, 20, 2)
print("\nEven numbers 0 to 18:")
print(even_numbers)

# Count backwards!
countdown = np.arange(10, 0, -1)
print("\nCountdown from 10 to 1:")
print(countdown)

Count 0 to 9:
[0 1 2 3 4 5 6 7 8 9]

Count 5 to 14:
[ 5  6  7  8  9 10 11 12 13 14]

Even numbers 0 to 18:
[ 0  2  4  6  8 10 12 14 16 18]

Countdown from 10 to 1:
[10  9  8  7  6  5  4  3  2  1]


In [10]:
# Using linspace (evenly spaced numbers)
# Like cutting a pizza into equal slices!

# Get 5 numbers evenly spaced between 0 and 1
five_slices = np.linspace(0, 1, 5)
print("5 equal slices between 0 and 1:")
print(five_slices)

# Get 11 numbers between 0 and 10 (includes both ends)
eleven_points = np.linspace(0, 10, 11)
print("\n11 points from 0 to 10:")
print(eleven_points)

print("\n💡 linspace always includes the start AND end number!")

5 equal slices between 0 and 1:
[0.   0.25 0.5  0.75 1.  ]

11 points from 0 to 10:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

💡 linspace always includes the start AND end number!


In [11]:
# Using logspace (logarithmically spaced - for science!)
# Numbers that grow exponentially (1, 10, 100, 1000...)
log_numbers = np.logspace(0, 3, 4)  # 10^0 to 10^3

print("Logarithmic spacing (powers of 10):")
print(log_numbers)
print("\n💡 These are: 10^0=1, 10^1=10, 10^2=100, 10^3=1000")

Logarithmic spacing (powers of 10):
[   1.   10.  100. 1000.]

💡 These are: 10^0=1, 10^1=10, 10^2=100, 10^3=1000


---
# 🔍 Part 2: Understanding Array Properties

Every array has special properties - like knowing how many students are in a classroom!

In [12]:
# Let's create an array and explore its properties
my_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Our array:")
print(my_array)
print("\n" + "="*50)

# Shape: tells us the dimensions (rows x columns)
print(f"\n📏 Shape: {my_array.shape}")
print("   This means: 3 rows and 4 columns")

# ndim: number of dimensions (1D, 2D, 3D, etc.)
print(f"\n📐 Number of dimensions: {my_array.ndim}")
print("   This is a 2D array (like a flat table)")

# size: total number of elements
print(f"\n🔢 Total elements: {my_array.size}")
print("   That's 3 rows × 4 columns = 12 numbers total")

# dtype: data type (what kind of numbers)
print(f"\n🏷️  Data type: {my_array.dtype}")
print("   These are integers (whole numbers)")

# itemsize: memory size of each element in bytes
print(f"\n💾 Size of each number: {my_array.itemsize} bytes")

# nbytes: total memory used
print(f"\n💾 Total memory used: {my_array.nbytes} bytes")
print(f"   That's {my_array.size} numbers × {my_array.itemsize} bytes each")

Our array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


📏 Shape: (3, 4)
   This means: 3 rows and 4 columns

📐 Number of dimensions: 2
   This is a 2D array (like a flat table)

🔢 Total elements: 12
   That's 3 rows × 4 columns = 12 numbers total

🏷️  Data type: int64
   These are integers (whole numbers)

💾 Size of each number: 8 bytes

💾 Total memory used: 96 bytes
   That's 12 numbers × 8 bytes each


In [13]:
# Comparing different dimensional arrays

# 1D array (a line)
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array (a line):")
print(array_1d)
print(f"Shape: {array_1d.shape} - Just 5 elements in a row")
print(f"Dimensions: {array_1d.ndim}D\n")

# 2D array (a table)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array (a table):")
print(array_2d)
print(f"Shape: {array_2d.shape} - 2 rows, 3 columns")
print(f"Dimensions: {array_2d.ndim}D\n")

# 3D array (stacked tables)
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array (stacked tables):")
print(array_3d)
print(f"Shape: {array_3d.shape} - 2 layers, 2 rows, 2 columns")
print(f"Dimensions: {array_3d.ndim}D")

1D Array (a line):
[1 2 3 4 5]
Shape: (5,) - Just 5 elements in a row
Dimensions: 1D

2D Array (a table):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3) - 2 rows, 3 columns
Dimensions: 2D

3D Array (stacked tables):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2) - 2 layers, 2 rows, 2 columns
Dimensions: 3D


---
# 🎨 Part 3: Data Types (Types of Numbers)

Just like you have different types of toys, NumPy has different types of numbers!

In [14]:
# Integer types (whole numbers: 1, 2, 3...)
# Different sizes use different amounts of memory

# Small integers (can store -128 to 127)
small_ints = np.array([1, 2, 3], dtype=np.int8)
print("Small integers (int8):")
print(small_ints)
print(f"Each number uses: {small_ints.itemsize} byte")
print("Good for: Small numbers to save memory\n")

# Medium integers (can store about -2 billion to 2 billion)
medium_ints = np.array([1000, 2000, 3000], dtype=np.int32)
print("Medium integers (int32):")
print(medium_ints)
print(f"Each number uses: {medium_ints.itemsize} bytes")
print("Good for: Most everyday numbers\n")

# Large integers (can store HUGE numbers)
large_ints = np.array([1000000, 2000000, 3000000], dtype=np.int64)
print("Large integers (int64):")
print(large_ints)
print(f"Each number uses: {large_ints.itemsize} bytes")
print("Good for: Really big numbers")

Small integers (int8):
[1 2 3]
Each number uses: 1 byte
Good for: Small numbers to save memory

Medium integers (int32):
[1000 2000 3000]
Each number uses: 4 bytes
Good for: Most everyday numbers

Large integers (int64):
[1000000 2000000 3000000]
Each number uses: 8 bytes
Good for: Really big numbers


In [15]:
# Float types (decimal numbers: 1.5, 2.7, 3.14...)

# Regular floats (good precision)
floats_32 = np.array([1.5, 2.7, 3.14], dtype=np.float32)
print("Regular floats (float32):")
print(floats_32)
print(f"Each number uses: {floats_32.itemsize} bytes\n")

# Double precision floats (very precise!)
floats_64 = np.array([1.5, 2.7, 3.14159265359], dtype=np.float64)
print("Double precision floats (float64):")
print(floats_64)
print(f"Each number uses: {floats_64.itemsize} bytes")
print("💡 Can store more decimal places!")

Regular floats (float32):
[1.5  2.7  3.14]
Each number uses: 4 bytes

Double precision floats (float64):
[1.5        2.7        3.14159265]
Each number uses: 8 bytes
💡 Can store more decimal places!


In [16]:
# Boolean type (True or False)
# Like yes/no questions!
bool_array = np.array([True, False, True, True, False])
print("Boolean array (True/False):")
print(bool_array)
print(f"Data type: {bool_array.dtype}")
print("\n💡 Useful for marking things as yes/no or on/off!")

Boolean array (True/False):
[ True False  True  True False]
Data type: bool

💡 Useful for marking things as yes/no or on/off!


In [17]:
# Complex numbers (for advanced math)
# Numbers with 'imaginary' parts: 1+2j
complex_array = np.array([1+2j, 3+4j, 5+6j])
print("Complex numbers:")
print(complex_array)
print(f"Data type: {complex_array.dtype}")
print("\n💡 Used in engineering and physics!")

Complex numbers:
[1.+2.j 3.+4.j 5.+6.j]
Data type: complex128

💡 Used in engineering and physics!


In [18]:
# Converting between types (type casting)
# Like turning a decimal number into a whole number

# Start with floats
float_array = np.array([1.7, 2.3, 3.9, 4.1])
print("Original (floats with decimals):")
print(float_array)

# Convert to integers (removes decimal part)
int_array = float_array.astype(int)
print("\nConverted to integers (decimals removed):")
print(int_array)
print("\n⚠️  Notice: 1.7 becomes 1, 3.9 becomes 3 (it cuts off, doesn't round!)")

# Convert integers to floats
back_to_float = int_array.astype(float)
print("\nBack to floats:")
print(back_to_float)
print("💡 Now they have .0 at the end!")

Original (floats with decimals):
[1.7 2.3 3.9 4.1]

Converted to integers (decimals removed):
[1 2 3 4]

⚠️  Notice: 1.7 becomes 1, 3.9 becomes 3 (it cuts off, doesn't round!)

Back to floats:
[1. 2. 3. 4.]
💡 Now they have .0 at the end!


---
# 🎯 Part 4: Indexing and Slicing (Finding Specific Numbers)

Imagine you're looking for a specific student in a classroom. Indexing helps you find them!

In [19]:
# 1D array indexing (like finding a person in a line)
# Remember: Python counts from 0!

students = np.array([10, 20, 30, 40, 50, 60, 70])
print("Students in a line:")
print(students)
print("\nPositions:  0   1   2   3   4   5   6")
print("           10  20  30  40  50  60  70\n")

# Get first student (position 0)
print(f"First student (index 0): {students[0]}")

# Get third student (position 2)
print(f"Third student (index 2): {students[2]}")

# Get last student (use -1)
print(f"Last student (index -1): {students[-1]}")

# Get second-to-last student
print(f"Second-to-last (index -2): {students[-2]}")

print("\n💡 Negative numbers count from the end!")

Students in a line:
[10 20 30 40 50 60 70]

Positions:  0   1   2   3   4   5   6
           10  20  30  40  50  60  70

First student (index 0): 10
Third student (index 2): 30
Last student (index -1): 70
Second-to-last (index -2): 60

💡 Negative numbers count from the end!


In [20]:
# Slicing (getting multiple elements at once)
# Like selecting a group of students

numbers = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
print("All numbers:")
print(numbers)
print("\nIndex:  0   1   2   3   4   5   6   7   8   9\n")

# Get elements from index 2 to 5 (not including 5)
slice1 = numbers[2:5]
print(f"numbers[2:5] = {slice1}")
print("Gets: index 2, 3, 4 (stops before 5)\n")

# Get first 4 elements
slice2 = numbers[:4]
print(f"numbers[:4] = {slice2}")
print("Gets: from start to index 3\n")

# Get last 3 elements
slice3 = numbers[-3:]
print(f"numbers[-3:] = {slice3}")
print("Gets: last 3 elements\n")

# Get every 2nd element
slice4 = numbers[::2]
print(f"numbers[::2] = {slice4}")
print("Gets: every 2nd element (step by 2)\n")

# Get every 3rd element starting from index 1
slice5 = numbers[1::3]
print(f"numbers[1::3] = {slice5}")
print("Gets: start at 1, then every 3rd\n")

# Reverse the array!
reversed_arr = numbers[::-1]
print(f"numbers[::-1] = {reversed_arr}")
print("💡 Negative step reverses the array!")

All numbers:
[ 0 10 20 30 40 50 60 70 80 90]

Index:  0   1   2   3   4   5   6   7   8   9

numbers[2:5] = [20 30 40]
Gets: index 2, 3, 4 (stops before 5)

numbers[:4] = [ 0 10 20 30]
Gets: from start to index 3

numbers[-3:] = [70 80 90]
Gets: last 3 elements

numbers[::2] = [ 0 20 40 60 80]
Gets: every 2nd element (step by 2)

numbers[1::3] = [10 40 70]
Gets: start at 1, then every 3rd

numbers[::-1] = [90 80 70 60 50 40 30 20 10  0]
💡 Negative step reverses the array!


In [21]:
# 2D array indexing (like finding a student in a classroom)
# You need [row, column]

classroom = np.array([
    [1,  2,  3,  4],   # Row 0
    [5,  6,  7,  8],   # Row 1
    [9, 10, 11, 12]    # Row 2
])

print("Classroom seating:")
print(classroom)
print("\n        Col0 Col1 Col2 Col3")
print("Row 0:    1    2    3    4")
print("Row 1:    5    6    7    8")
print("Row 2:    9   10   11   12\n")

# Get element at row 1, column 2
print(f"classroom[1, 2] = {classroom[1, 2]}")
print("This is row 1, column 2 = 7\n")

# Get entire first row
print(f"First row classroom[0] = {classroom[0]}")
print("Gets all of row 0\n")

# Get entire first column
print(f"First column classroom[:, 0] = {classroom[:, 0]}")
print("Gets column 0 from all rows\n")

# Get last column
print(f"Last column classroom[:, -1] = {classroom[:, -1]}")
print("Gets the last column from all rows")

Classroom seating:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

        Col0 Col1 Col2 Col3
Row 0:    1    2    3    4
Row 1:    5    6    7    8
Row 2:    9   10   11   12

classroom[1, 2] = 7
This is row 1, column 2 = 7

First row classroom[0] = [1 2 3 4]
Gets all of row 0

First column classroom[:, 0] = [1 5 9]
Gets column 0 from all rows

Last column classroom[:, -1] = [ 4  8 12]
Gets the last column from all rows


In [22]:
# 2D slicing (getting sub-grids)

grid = np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

print("Full grid:")
print(grid)
print()

# Get a 2x2 sub-grid from top-left
sub_grid = grid[0:2, 0:2]
print("Top-left 2x2 corner grid[0:2, 0:2]:")
print(sub_grid)
print("Gets rows 0-1, columns 0-1\n")

# Get middle section
middle = grid[1:3, 1:4]
print("Middle section grid[1:3, 1:4]:")
print(middle)
print("Gets rows 1-2, columns 1-3\n")

# Get every other element in both dimensions
sparse = grid[::2, ::2]
print("Every other element grid[::2, ::2]:")
print(sparse)
print("💡 Like a checkerboard pattern!")

Full grid:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Top-left 2x2 corner grid[0:2, 0:2]:
[[1 2]
 [6 7]]
Gets rows 0-1, columns 0-1

Middle section grid[1:3, 1:4]:
[[ 7  8  9]
 [12 13 14]]
Gets rows 1-2, columns 1-3

Every other element grid[::2, ::2]:
[[ 1  3  5]
 [11 13 15]]
💡 Like a checkerboard pattern!


In [23]:
# Boolean indexing (finding elements that match a condition)
# Like finding all students taller than 5 feet!

scores = np.array([45, 67, 89, 23, 91, 78, 56, 34, 88, 92])
print("Test scores:")
print(scores)
print()

# Find which scores are above 70
above_70 = scores > 70
print("Which scores are above 70? (True/False)")
print(above_70)
print()

# Get the actual scores above 70
high_scores = scores[scores > 70]
print("Scores above 70:")
print(high_scores)
print(f"Found {len(high_scores)} high scores!\n")

# Find scores between 50 and 80
middle_scores = scores[(scores >= 50) & (scores <= 80)]
print("Scores between 50 and 80:")
print(middle_scores)
print("\n💡 Use & for 'and', | for 'or' with conditions!")

# Find failing scores (below 60)
failing = scores[scores < 60]
print(f"\nFailing scores (below 60): {failing}")
print(f"Number of students who need help: {len(failing)}")

Test scores:
[45 67 89 23 91 78 56 34 88 92]

Which scores are above 70? (True/False)
[False False  True False  True  True False False  True  True]

Scores above 70:
[89 91 78 88 92]
Found 5 high scores!

Scores between 50 and 80:
[67 78 56]

💡 Use & for 'and', | for 'or' with conditions!

Failing scores (below 60): [45 23 56 34]
Number of students who need help: 4


In [24]:
# Fancy indexing (using arrays of indices)
# Like picking specific students by their ID numbers

students = np.array([100, 200, 300, 400, 500, 600, 700, 800])
print("All students:")
print(students)
print("Index:  0    1    2    3    4    5    6    7\n")

# Pick students at specific positions
pick_these = np.array([0, 3, 5, 7])  # Pick 1st, 4th, 6th, and 8th
selected = students[pick_these]
print(f"Pick indices {pick_these}:")
print(selected)
print("\n💡 We picked specific students by their positions!")

All students:
[100 200 300 400 500 600 700 800]
Index:  0    1    2    3    4    5    6    7

Pick indices [0 3 5 7]:
[100 400 600 800]

💡 We picked specific students by their positions!


---
# 🔄 Part 5: Reshaping Arrays (Changing the Shape)

Imagine you have 12 students. You can arrange them as:
- 1 row of 12
- 2 rows of 6
- 3 rows of 4
- 4 rows of 3
- 6 rows of 2
- 12 rows of 1

Same students, different arrangements!

In [25]:
# Start with a 1D array (a line of numbers)
numbers = np.arange(1, 13)  # Numbers 1 to 12
print("Original (1D line of 12 numbers):")
print(numbers)
print(f"Shape: {numbers.shape}\n")

# Reshape to 3 rows, 4 columns
grid_3x4 = numbers.reshape(3, 4)
print("Reshaped to 3 rows × 4 columns:")
print(grid_3x4)
print(f"Shape: {grid_3x4.shape}\n")

# Reshape to 4 rows, 3 columns
grid_4x3 = numbers.reshape(4, 3)
print("Reshaped to 4 rows × 3 columns:")
print(grid_4x3)
print(f"Shape: {grid_4x3.shape}\n")

# Reshape to 2 rows, 6 columns
grid_2x6 = numbers.reshape(2, 6)
print("Reshaped to 2 rows × 6 columns:")
print(grid_2x6)
print(f"Shape: {grid_2x6.shape}")

print("\n💡 The total number of elements stays the same: 12!")

Original (1D line of 12 numbers):
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped to 3 rows × 4 columns:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

Reshaped to 4 rows × 3 columns:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)

Reshaped to 2 rows × 6 columns:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape: (2, 6)

💡 The total number of elements stays the same: 12!


In [26]:
# Using -1 to let NumPy figure out one dimension
# Like saying "I want 3 rows, you figure out how many columns!"

numbers = np.arange(1, 25)  # 24 numbers
print("24 numbers:")
print(numbers)
print()

# I want 4 rows, NumPy figures out columns
auto_shape1 = numbers.reshape(4, -1)
print("Reshape to 4 rows, auto columns:")
print(auto_shape1)
print(f"NumPy made it: {auto_shape1.shape} (4 rows, 6 columns)\n")

# I want 6 columns, NumPy figures out rows
auto_shape2 = numbers.reshape(-1, 6)
print("Reshape to auto rows, 6 columns:")
print(auto_shape2)
print(f"NumPy made it: {auto_shape2.shape} (4 rows, 6 columns)")

print("\n💡 Use -1 when you want NumPy to calculate one dimension!")

24 numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Reshape to 4 rows, auto columns:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
NumPy made it: (4, 6) (4 rows, 6 columns)

Reshape to auto rows, 6 columns:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
NumPy made it: (4, 6) (4 rows, 6 columns)

💡 Use -1 when you want NumPy to calculate one dimension!


In [27]:
# Flattening (turning any shape into a 1D line)
# Like making all students stand in a single line

grid = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 3x3 grid:")
print(grid)
print(f"Shape: {grid.shape}\n")

# Method 1: flatten() - makes a copy
flat1 = grid.flatten()
print("After flatten():")
print(flat1)
print(f"Shape: {flat1.shape}\n")

# Method 2: ravel() - tries to avoid copying
flat2 = grid.ravel()
print("After ravel():")
print(flat2)
print(f"Shape: {flat2.shape}")

print("\n💡 Both methods make a 1D array, but ravel() is faster!")

Original 3x3 grid:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

After flatten():
[1 2 3 4 5 6 7 8 9]
Shape: (9,)

After ravel():
[1 2 3 4 5 6 7 8 9]
Shape: (9,)

💡 Both methods make a 1D array, but ravel() is faster!


In [28]:
# Transpose (flip rows and columns)
# Like rotating a table 90 degrees!

original = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print("Original (2 rows, 4 columns):")
print(original)
print(f"Shape: {original.shape}\n")

# Transpose it
transposed = original.T
print("After transpose (4 rows, 2 columns):")
print(transposed)
print(f"Shape: {transposed.shape}")

print("\n💡 Rows became columns, columns became rows!")
print("First row [1,2,3,4] became first column!")

Original (2 rows, 4 columns):
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)

After transpose (4 rows, 2 columns):
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
Shape: (4, 2)

💡 Rows became columns, columns became rows!
First row [1,2,3,4] became first column!


In [29]:
# Adding and removing dimensions
# Like turning a line into a column or row

line = np.array([1, 2, 3, 4, 5])
print("Original line:")
print(line)
print(f"Shape: {line.shape} (just 5 elements)\n")

# Make it a column (5 rows, 1 column)
column = line[:, np.newaxis]
print("As a column:")
print(column)
print(f"Shape: {column.shape} (5 rows, 1 column)\n")

# Make it a row (1 row, 5 columns)
row = line[np.newaxis, :]
print("As a row:")
print(row)
print(f"Shape: {row.shape} (1 row, 5 columns)\n")

# Remove extra dimensions with squeeze
squeezed = column.squeeze()
print("After squeeze (back to line):")
print(squeezed)
print(f"Shape: {squeezed.shape}")

print("\n💡 newaxis adds dimensions, squeeze removes them!")

Original line:
[1 2 3 4 5]
Shape: (5,) (just 5 elements)

As a column:
[[1]
 [2]
 [3]
 [4]
 [5]]
Shape: (5, 1) (5 rows, 1 column)

As a row:
[[1 2 3 4 5]]
Shape: (1, 5) (1 row, 5 columns)

After squeeze (back to line):
[1 2 3 4 5]
Shape: (5,)

💡 newaxis adds dimensions, squeeze removes them!


---
# ➕ Part 6: Basic Operations (Math on Arrays)

The magic of NumPy: do math on ALL numbers at once!

In [30]:
# Element-wise operations (each element gets the operation)
# Like giving everyone in class the same homework!

prices = np.array([10, 20, 30, 40, 50])
print("Original prices ($):")
print(prices)
print()

# Add $5 to all prices
increased = prices + 5
print("After $5 increase:")
print(increased)
print("💡 Added 5 to EVERY price at once!\n")

# 20% discount (multiply by 0.8)
discounted = prices * 0.8
print("After 20% discount:")
print(discounted)
print("💡 Multiplied EVERY price by 0.8!\n")

# Double all prices
doubled = prices * 2
print("Doubled prices:")
print(doubled)
print()

# Square all prices (price²)
squared = prices ** 2
print("Squared prices:")
print(squared)
print("💡 10² = 100, 20² = 400, etc.")

Original prices ($):
[10 20 30 40 50]

After $5 increase:
[15 25 35 45 55]
💡 Added 5 to EVERY price at once!

After 20% discount:
[ 8. 16. 24. 32. 40.]
💡 Multiplied EVERY price by 0.8!

Doubled prices:
[ 20  40  60  80 100]

Squared prices:
[ 100  400  900 1600 2500]
💡 10² = 100, 20² = 400, etc.


In [31]:
# Operations between two arrays
# Like comparing two teams' scores!

team_a = np.array([10, 20, 30, 40])
team_b = np.array([5, 15, 25, 35])

print("Team A scores:", team_a)
print("Team B scores:", team_b)
print()

# Add scores together
total = team_a + team_b
print("Combined scores:", total)
print("(10+5=15, 20+15=35, 30+25=55, 40+35=75)\n")

# Find the difference
difference = team_a - team_b
print("Score differences:", difference)
print("(Team A - Team B for each game)\n")

# Multiply scores
multiplied = team_a * team_b
print("Multiplied:", multiplied)
print("(10×5=50, 20×15=300, etc.)\n")

# Divide scores
divided = team_a / team_b
print("Divided (A/B):", divided)
print("(Shows how many times bigger A is than B)")

Team A scores: [10 20 30 40]
Team B scores: [ 5 15 25 35]

Combined scores: [15 35 55 75]
(10+5=15, 20+15=35, 30+25=55, 40+35=75)

Score differences: [5 5 5 5]
(Team A - Team B for each game)

Multiplied: [  50  300  750 1400]
(10×5=50, 20×15=300, etc.)

Divided (A/B): [2.         1.33333333 1.2        1.14285714]
(Shows how many times bigger A is than B)


In [32]:
# Comparison operations
# Like comparing heights or ages!

ages_group1 = np.array([10, 15, 20, 25, 30])
ages_group2 = np.array([12, 15, 18, 28, 25])

print("Group 1 ages:", ages_group1)
print("Group 2 ages:", ages_group2)
print()

# Who is older?
group1_older = ages_group1 > ages_group2
print("Is Group 1 older?", group1_older)
print("(Compares each pair: 10>12? 15>15? 20>18? etc.)\n")

# Who is the same age?
same_age = ages_group1 == ages_group2
print("Same age?", same_age)
print("(Only the 2nd pair is equal: 15==15)\n")

# Find adults (18 or older) in group 1
adults = ages_group1 >= 18
print("Adults in Group 1 (18+):", adults)
print("Ages of adults:", ages_group1[adults])

Group 1 ages: [10 15 20 25 30]
Group 2 ages: [12 15 18 28 25]

Is Group 1 older? [False False  True False  True]
(Compares each pair: 10>12? 15>15? 20>18? etc.)

Same age? [False  True False False False]
(Only the 2nd pair is equal: 15==15)

Adults in Group 1 (18+): [False False  True  True  True]
Ages of adults: [20 25 30]


In [33]:
# Aggregation functions (summarizing data)
# Like finding class statistics!

test_scores = np.array([85, 92, 78, 90, 88, 76, 95, 82, 89, 91])

print("Test scores:", test_scores)
print("\n📊 Statistics:")
print("="*40)

# Sum (total of all scores)
total = np.sum(test_scores)
print(f"Total points: {total}")

# Mean (average)
average = np.mean(test_scores)
print(f"Average score: {average:.2f}")

# Median (middle value)
median = np.median(test_scores)
print(f"Median score: {median}")

# Standard deviation (how spread out)
std = np.std(test_scores)
print(f"Standard deviation: {std:.2f}")
print("  (Lower = scores are similar, Higher = scores vary a lot)")

# Min and Max
lowest = np.min(test_scores)
highest = np.max(test_scores)
print(f"\nLowest score: {lowest}")
print(f"Highest score: {highest}")
print(f"Range: {highest - lowest} points")

# Find positions of min and max
worst_student = np.argmin(test_scores)
best_student = np.argmax(test_scores)
print(f"\nWorst score at position: {worst_student}")
print(f"Best score at position: {best_student}")

Test scores: [85 92 78 90 88 76 95 82 89 91]

📊 Statistics:
Total points: 866
Average score: 86.60
Median score: 88.5
Standard deviation: 5.90
  (Lower = scores are similar, Higher = scores vary a lot)

Lowest score: 76
Highest score: 95
Range: 19 points

Worst score at position: 5
Best score at position: 6


In [34]:
# Operations on 2D arrays (with axis parameter)
# axis=0 means "down the columns"
# axis=1 means "across the rows"

# Imagine a grade book: rows=students, columns=tests
grades = np.array([
    [85, 90, 78],  # Student 1's scores
    [92, 88, 95],  # Student 2's scores
    [78, 85, 82],  # Student 3's scores
    [90, 92, 88]   # Student 4's scores
])

print("Grade book (rows=students, columns=tests):")
print(grades)
print("\n        Test1 Test2 Test3")
print()

# Average for each student (across rows)
student_averages = np.mean(grades, axis=1)
print("Each student's average (axis=1):")
print(student_averages)
print("Student 1: (85+90+78)/3 = 84.33")
print()

# Average for each test (down columns)
test_averages = np.mean(grades, axis=0)
print("Each test's average (axis=0):")
print(test_averages)
print("Test 1: (85+92+78+90)/4 = 86.25")
print()

# Overall class average
class_average = np.mean(grades)
print(f"Overall class average: {class_average:.2f}")

print("\n💡 axis=0: operate down columns")
print("💡 axis=1: operate across rows")
print("💡 no axis: operate on everything!")

Grade book (rows=students, columns=tests):
[[85 90 78]
 [92 88 95]
 [78 85 82]
 [90 92 88]]

        Test1 Test2 Test3

Each student's average (axis=1):
[84.33333333 91.66666667 81.66666667 90.        ]
Student 1: (85+90+78)/3 = 84.33

Each test's average (axis=0):
[86.25 88.75 85.75]
Test 1: (85+92+78+90)/4 = 86.25

Overall class average: 86.92

💡 axis=0: operate down columns
💡 axis=1: operate across rows
💡 no axis: operate on everything!


---
# 📡 Part 7: Broadcasting (Smart Array Operations)

Broadcasting is NumPy's superpower! It lets you do math between arrays of different shapes without copying data.

In [35]:
# Broadcasting Rule 1: Scalar with Array
# A single number can be used with any array!

arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
print("Add 10 to all:", arr + 10)
print("Multiply all by 3:", arr * 3)

print("\n💡 The scalar 10 is 'broadcast' to match the array shape!")

Original array: [1 2 3 4 5]
Add 10 to all: [11 12 13 14 15]
Multiply all by 3: [ 3  6  9 12 15]

💡 The scalar 10 is 'broadcast' to match the array shape!


In [36]:
# Broadcasting Rule 2: 1D array with 2D array
# Like adding a row to every row in a table!

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row_to_add = np.array([10, 20, 30])

print("Matrix:")
print(matrix)
print("\nRow to add:", row_to_add)
print("\nResult (add row to each row of matrix):")
print(matrix + row_to_add)

print("\n💡 The row [10, 20, 30] was added to EACH row of the matrix!")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row to add: [10 20 30]

Result (add row to each row of matrix):
[[11 22 33]
 [14 25 36]
 [17 28 39]]

💡 The row [10, 20, 30] was added to EACH row of the matrix!


In [37]:
# Broadcasting Rule 3: Column with Matrix
# Adding a column to every column!

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

column_to_add = np.array([[10], [20], [30]])

print("Matrix:")
print(matrix)
print("\nColumn to add:")
print(column_to_add)
print("\nResult:")
print(matrix + column_to_add)

print("\n💡 Each row got its corresponding value: row 0 +10, row 1 +20, row 2 +30!")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Column to add:
[[10]
 [20]
 [30]]

Result:
[[11 12 13]
 [24 25 26]
 [37 38 39]]

💡 Each row got its corresponding value: row 0 +10, row 1 +20, row 2 +30!


In [38]:
# Real-world Broadcasting Example: Normalizing data
# Like converting test scores to percentages!

scores = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [78, 85, 82]
])

print("Raw scores:")
print(scores)

# Find max score for each test (column)
max_scores = np.max(scores, axis=0)
print(f"\nMax score per test: {max_scores}")

# Convert to percentages (divide each column by its max)
percentages = (scores / max_scores) * 100
print("\nAs percentages:")
print(percentages.round(2))

print("\n💡 Broadcasting divided each column by its max automatically!")

Raw scores:
[[85 90 78]
 [92 88 95]
 [78 85 82]]

Max score per test: [92 90 95]

As percentages:
[[ 92.39 100.    82.11]
 [100.    97.78 100.  ]
 [ 84.78  94.44  86.32]]

💡 Broadcasting divided each column by its max automatically!


---
# 🔢 Part 8: Linear Algebra (Matrix Math)

NumPy has powerful tools for matrix operations - essential for machine learning and data science!

In [39]:
# Matrix multiplication (dot product)
# Different from element-wise multiplication!

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Element-wise multiplication (each element multiplied)
elementwise = A * B
print("\nElement-wise (A * B):")
print(elementwise)

# Matrix multiplication (proper linear algebra)
matrix_mult = np.dot(A, B)
print("\nMatrix multiplication (np.dot(A, B)):")
print(matrix_mult)

# Alternative: @ operator (Python 3.5+)
matrix_mult2 = A @ B
print("\nUsing @ operator (A @ B):")
print(matrix_mult2)

print("\n💡 Matrix multiplication: row × column sums!")

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Element-wise (A * B):
[[ 5 12]
 [21 32]]

Matrix multiplication (np.dot(A, B)):
[[19 22]
 [43 50]]

Using @ operator (A @ B):
[[19 22]
 [43 50]]

💡 Matrix multiplication: row × column sums!


In [40]:
# Matrix inverse and determinant
# Like finding the "undo" button for a matrix!

matrix = np.array([[4, 7], [2, 6]])
print("Original matrix:")
print(matrix)

# Determinant (tells if matrix is invertible)
det = np.linalg.det(matrix)
print(f"\nDeterminant: {det}")
print("💡 If determinant ≠ 0, matrix can be inverted!")

# Inverse (the "undo" matrix)
inverse = np.linalg.inv(matrix)
print("\nInverse matrix:")
print(inverse)

# Verify: matrix × inverse = identity matrix
identity = matrix @ inverse
print("\nMatrix × Inverse (should be identity):")
print(identity.round(10))

print("\n💡 Multiplying a matrix by its inverse gives the identity matrix!")

Original matrix:
[[4 7]
 [2 6]]

Determinant: 10.000000000000002
💡 If determinant ≠ 0, matrix can be inverted!

Inverse matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]

Matrix × Inverse (should be identity):
[[ 1. -0.]
 [ 0.  1.]]

💡 Multiplying a matrix by its inverse gives the identity matrix!


In [41]:
# Solving systems of linear equations
# Like solving: 2x + 3y = 8 and 4x + y = 10

# Coefficients matrix
A = np.array([[2, 3], [4, 1]])
# Results vector
b = np.array([8, 10])

print("Solving system of equations:")
print("2x + 3y = 8")
print("4x + 1y = 10")

# Solve for x and y
solution = np.linalg.solve(A, b)
print(f"\nSolution: x = {solution[0]}, y = {solution[1]}")

# Verify the solution
print("\nVerification:")
print(f"2({solution[0]}) + 3({solution[1]}) = {2*solution[0] + 3*solution[1]}")
print(f"4({solution[0]}) + 1({solution[1]}) = {4*solution[0] + 1*solution[1]}")

print("\n💡 np.linalg.solve() finds the solution automatically!")

Solving system of equations:
2x + 3y = 8
4x + 1y = 10

Solution: x = 2.2, y = 1.2

Verification:
2(2.2) + 3(1.2) = 8.0
4(2.2) + 1(1.2) = 10.0

💡 np.linalg.solve() finds the solution automatically!


In [42]:
# Eigenvalues and Eigenvectors
# Important for data science and machine learning!

matrix = np.array([[4, 2], [1, 3]])
print("Matrix:")
print(matrix)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(f"\nEigenvalues: {eigenvalues}")
print("\nEigenvectors:")
print(eigenvectors)

print("\n💡 Used in PCA (Principal Component Analysis) for data reduction!")
print("💡 Eigenvalues show importance, eigenvectors show direction!")

Matrix:
[[4 2]
 [1 3]]

Eigenvalues: [5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

💡 Used in PCA (Principal Component Analysis) for data reduction!
💡 Eigenvalues show importance, eigenvectors show direction!


In [43]:
# Matrix norms and traces

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)

# Trace (sum of diagonal elements)
trace = np.trace(matrix)
print(f"\nTrace (sum of diagonal): {trace}")
print("1 + 5 + 9 = 15")

# Matrix rank
rank = np.linalg.matrix_rank(matrix)
print(f"\nMatrix rank: {rank}")
print("💡 Rank tells us the number of independent rows/columns")

# Frobenius norm (like distance in matrix space)
norm = np.linalg.norm(matrix)
print(f"\nFrobenius norm: {norm:.2f}")
print("💡 Measures the 'size' of the matrix")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trace (sum of diagonal): 15
1 + 5 + 9 = 15

Matrix rank: 2
💡 Rank tells us the number of independent rows/columns

Frobenius norm: 16.88
💡 Measures the 'size' of the matrix


---
# 🎲 Part 9: Random Number Generation

NumPy can generate random numbers for simulations, testing, and machine learning!

In [44]:
# Setting a seed for reproducibility
# Like saving your random number generator's state!

np.random.seed(42)
print("With seed 42:")
print(np.random.rand(5))

np.random.seed(42)
print("\nWith same seed 42 again (same numbers!):")
print(np.random.rand(5))

print("\n💡 Seeds make 'random' numbers reproducible - great for testing!")

With seed 42:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

With same seed 42 again (same numbers!):
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

💡 Seeds make 'random' numbers reproducible - great for testing!


In [45]:
# Random floats between 0 and 1
random_floats = np.random.rand(3, 4)
print("Random floats (0 to 1):")
print(random_floats)

# Random floats from standard normal distribution (mean=0, std=1)
normal = np.random.randn(3, 4)
print("\nRandom from normal distribution:")
print(normal)

# Random integers
random_ints = np.random.randint(1, 100, size=(3, 4))
print("\nRandom integers (1 to 99):")
print(random_ints)

print("\n💡 rand() = uniform [0,1], randn() = normal, randint() = integers")

Random floats (0 to 1):
[[0.15599452 0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451 0.30424224]]

Random from normal distribution:
[[-2.61254901  0.95036968  0.81644508 -1.523876  ]
 [-0.42804606 -0.74240684 -0.7033438  -2.13962066]
 [-0.62947496  0.59772047  2.55948803  0.39423302]]

Random integers (1 to 99):
[[ 3 51  7 21]
 [73 39 18  4]
 [89 60 14  9]]

💡 rand() = uniform [0,1], randn() = normal, randint() = integers


In [46]:
# Random choice and shuffle
# Like picking lottery numbers or shuffling cards!

# Pick random elements from an array
colors = np.array(['red', 'blue', 'green', 'yellow', 'purple'])
chosen = np.random.choice(colors, size=3)
print("Randomly chosen colors:", chosen)

# Pick with replacement=False (no duplicates)
unique_chosen = np.random.choice(colors, size=3, replace=False)
print("Unique random colors:", unique_chosen)

# Shuffle an array in place
deck = np.arange(1, 11)
print(f"\nOriginal deck: {deck}")
np.random.shuffle(deck)
print(f"Shuffled deck: {deck}")

# Permutation (shuffle without modifying original)
original = np.arange(1, 6)
shuffled = np.random.permutation(original)
print(f"\nOriginal: {original}")
print(f"Permuted: {shuffled}")

print("\n💡 choice() picks random items, shuffle() mixes them up!")

Randomly chosen colors: ['blue' 'purple' 'blue']
Unique random colors: ['red' 'blue' 'green']

Original deck: [ 1  2  3  4  5  6  7  8  9 10]
Shuffled deck: [ 5  9  2  4  1  6  3 10  8  7]

Original: [1 2 3 4 5]
Permuted: [1 3 5 2 4]

💡 choice() picks random items, shuffle() mixes them up!


In [47]:
# Different probability distributions

# Uniform distribution (all values equally likely)
uniform = np.random.uniform(low=0, high=10, size=5)
print("Uniform distribution (0 to 10):", uniform)

# Normal (Gaussian) distribution
normal = np.random.normal(loc=100, scale=15, size=5)
print("\nNormal distribution (mean=100, std=15):", normal.round(2))

# Binomial distribution (coin flips)
coin_flips = np.random.binomial(n=10, p=0.5, size=5)
print("\nBinomial (10 coin flips, 5 trials):", coin_flips)
print("(Number of heads in 10 flips, repeated 5 times)")

# Poisson distribution (events per time period)
events = np.random.poisson(lam=3, size=5)
print("\nPoisson (average 3 events):", events)
print("(Like customers arriving per hour)")

print("\n💡 Different distributions model different real-world phenomena!")

Uniform distribution (0 to 10): [2.07941663 5.67700328 0.31313292 8.42284775 4.49754133]

Normal distribution (mean=100, std=15): [110.48  97.43  86.39 117.83 111.78]

Binomial (10 coin flips, 5 trials): [8 7 6 5 5]
(Number of heads in 10 flips, repeated 5 times)

Poisson (average 3 events): [3 1 2 0 5]
(Like customers arriving per hour)

💡 Different distributions model different real-world phenomena!


---
# 🔍 Part 10: Sorting and Searching

Finding and organizing data efficiently!

In [48]:
# Sorting arrays

unsorted = np.array([64, 25, 12, 22, 11, 90, 88, 45])
print("Unsorted:", unsorted)

# Sort (returns new sorted array)
sorted_arr = np.sort(unsorted)
print("Sorted:", sorted_arr)
print("Original unchanged:", unsorted)

# Sort in place (modifies original)
unsorted.sort()
print("After in-place sort:", unsorted)

# Sort in descending order
descending = np.sort(unsorted)[::-1]
print("Descending order:", descending)

print("\n💡 np.sort() returns new array, .sort() modifies in place!")

Unsorted: [64 25 12 22 11 90 88 45]
Sorted: [11 12 22 25 45 64 88 90]
Original unchanged: [64 25 12 22 11 90 88 45]
After in-place sort: [11 12 22 25 45 64 88 90]
Descending order: [90 88 64 45 25 22 12 11]

💡 np.sort() returns new array, .sort() modifies in place!


In [49]:
# Argsort - get indices that would sort the array
# Like getting the ranking positions!

scores = np.array([85, 92, 78, 95, 88])
names = np.array(['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'])

print("Scores:", scores)
print("Names:", names)

# Get indices that would sort the scores
sorted_indices = np.argsort(scores)
print(f"\nIndices to sort scores: {sorted_indices}")

# Use indices to sort both arrays
print("\nSorted by score:")
for idx in sorted_indices:
    print(f"{names[idx]}: {scores[idx]}")

# Get top 3 (descending)
top_3_indices = np.argsort(scores)[-3:][::-1]
print("\nTop 3 students:")
for idx in top_3_indices:
    print(f"{names[idx]}: {scores[idx]}")

print("\n💡 argsort() gives you the positions, not the sorted values!")

Scores: [85 92 78 95 88]
Names: ['Alice' 'Bob' 'Charlie' 'Diana' 'Eve']

Indices to sort scores: [2 0 4 1 3]

Sorted by score:
Charlie: 78
Alice: 85
Eve: 88
Bob: 92
Diana: 95

Top 3 students:
Diana: 95
Bob: 92
Eve: 88

💡 argsort() gives you the positions, not the sorted values!


In [50]:
# Sorting 2D arrays

grades = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [78, 85, 82],
    [90, 92, 88]
])

print("Original grades:")
print(grades)

# Sort each row
sorted_rows = np.sort(grades, axis=1)
print("\nEach row sorted:")
print(sorted_rows)

# Sort each column
sorted_cols = np.sort(grades, axis=0)
print("\nEach column sorted:")
print(sorted_cols)

# Sort by first column (sort entire rows based on first value)
sorted_by_col0 = grades[grades[:, 0].argsort()]
print("\nRows sorted by first column:")
print(sorted_by_col0)

print("\n💡 axis=1 sorts rows, axis=0 sorts columns!")

Original grades:
[[85 90 78]
 [92 88 95]
 [78 85 82]
 [90 92 88]]

Each row sorted:
[[78 85 90]
 [88 92 95]
 [78 82 85]
 [88 90 92]]

Each column sorted:
[[78 85 78]
 [85 88 82]
 [90 90 88]
 [92 92 95]]

Rows sorted by first column:
[[78 85 82]
 [85 90 78]
 [90 92 88]
 [92 88 95]]

💡 axis=1 sorts rows, axis=0 sorts columns!


In [51]:
# Searching in arrays

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Find where condition is true
greater_than_50 = np.where(arr > 50)
print("Indices where value > 50:", greater_than_50[0])
print("Values:", arr[greater_than_50])

# Find first occurrence
first_match = np.argmax(arr > 50)
print(f"\nFirst index where value > 50: {first_match}")

# Count how many match condition
count = np.sum(arr > 50)
print(f"Count of values > 50: {count}")

# Check if any/all match condition
has_large = np.any(arr > 100)
all_positive = np.all(arr > 0)
print(f"\nAny value > 100? {has_large}")
print(f"All values > 0? {all_positive}")

print("\n💡 where() finds indices, any() checks if at least one, all() checks if every one!")

Indices where value > 50: [5 6 7 8]
Values: [60 70 80 90]

First index where value > 50: 5
Count of values > 50: 4

Any value > 100? False
All values > 0? True

💡 where() finds indices, any() checks if at least one, all() checks if every one!


In [52]:
# np.searchsorted - find insertion index in sorted array
# Like finding where to insert a new student in a sorted line!

sorted_ages = np.array([18, 22, 25, 30, 35, 40, 45])
print("Sorted ages:", sorted_ages)

# Where would 28 fit?
insert_pos = np.searchsorted(sorted_ages, 28)
print(f"\nInsert 28 at index: {insert_pos}")
print(f"Result: {np.insert(sorted_ages, insert_pos, 28)}")

# Multiple values
new_ages = [20, 32, 50]
positions = np.searchsorted(sorted_ages, new_ages)
print(f"\nInsert {new_ages} at indices: {positions}")

print("\n💡 searchsorted() finds where to insert to keep array sorted!")

Sorted ages: [18 22 25 30 35 40 45]

Insert 28 at index: 3
Result: [18 22 25 28 30 35 40 45]

Insert [20, 32, 50] at indices: [1 4 7]

💡 searchsorted() finds where to insert to keep array sorted!


---
# 🎯 Part 11: Advanced Indexing with where, select, and choose

Powerful tools for conditional operations!

In [53]:
# np.where - conditional selection
# Like an if-else for arrays!

scores = np.array([45, 67, 89, 23, 91, 78, 56, 34, 88, 92])
print("Scores:", scores)

# Replace: if score >= 60, keep it, else make it 0
adjusted = np.where(scores >= 60, scores, 0)
print("\nPass (>=60) or 0:", adjusted)

# Grade assignment: A (>=90), B (>=80), C otherwise
grades = np.where(scores >= 90, 'A',
                  np.where(scores >= 80, 'B', 'C'))
print("\nGrades:", grades)

# Double passing scores, halve failing scores
modified = np.where(scores >= 60, scores * 2, scores / 2)
print("\nModified scores:", modified)

print("\n💡 np.where(condition, value_if_true, value_if_false)")

Scores: [45 67 89 23 91 78 56 34 88 92]

Pass (>=60) or 0: [ 0 67 89  0 91 78  0  0 88 92]

Grades: ['C' 'C' 'B' 'C' 'A' 'C' 'C' 'C' 'B' 'A']

Modified scores: [ 22.5 134.  178.   11.5 182.  156.   28.   17.  176.  184. ]

💡 np.where(condition, value_if_true, value_if_false)


In [54]:
# np.select - multiple conditions
# Like a switch/case statement!

ages = np.array([5, 12, 18, 25, 45, 70, 8, 16, 35, 80])
print("Ages:", ages)

# Define conditions
conditions = [
    ages < 13,           # Child
    (ages >= 13) & (ages < 20),  # Teen
    (ages >= 20) & (ages < 65),  # Adult
    ages >= 65           # Senior
]

# Define corresponding values
choices = ['Child', 'Teen', 'Adult', 'Senior']

# Apply conditions
categories = np.select(conditions, choices, default='Unknown')
print("\nAge categories:", categories)

# Another example: pricing tiers
prices = np.array([5, 15, 25, 50, 75, 120, 200])
conditions = [
    prices < 10,
    (prices >= 10) & (prices < 50),
    (prices >= 50) & (prices < 100),
    prices >= 100
]
tiers = ['Budget', 'Standard', 'Premium', 'Luxury']
product_tiers = np.select(conditions, tiers)
print(f"\nPrices: {prices}")
print(f"Tiers: {product_tiers}")

print("\n💡 np.select() handles multiple conditions elegantly!")

Ages: [ 5 12 18 25 45 70  8 16 35 80]

Age categories: ['Child' 'Child' 'Teen' 'Adult' 'Adult' 'Senior' 'Child' 'Teen' 'Adult'
 'Senior']

Prices: [  5  15  25  50  75 120 200]
Tiers: ['Budget' 'Standard' 'Standard' 'Premium' 'Premium' 'Luxury' 'Luxury']

💡 np.select() handles multiple conditions elegantly!


In [55]:
# np.choose - pick from multiple arrays based on index array

# Index array (which array to pick from for each position)
indices = np.array([0, 1, 2, 0, 1, 2])

# Choice arrays
choices = [
    [10, 10, 10, 10, 10, 10],  # Choice 0
    [20, 20, 20, 20, 20, 20],  # Choice 1
    [30, 30, 30, 30, 30, 30]   # Choice 2
]

result = np.choose(indices, choices)
print("Indices:", indices)
print("Result:", result)
print("Picked: 10, 20, 30, 10, 20, 30")

# Practical example: select operation based on code
operations = np.array([0, 1, 2, 0, 2, 1])
x = np.array([5, 5, 5, 5, 5, 5])
results = np.choose(operations, [x, x*2, x**2])
print(f"\nOperations {operations} on {x}:")
print(f"Results: {results}")
print("(0=keep, 1=double, 2=square)")

print("\n💡 np.choose() picks values from different arrays based on indices!")

Indices: [0 1 2 0 1 2]
Result: [10 20 30 10 20 30]
Picked: 10, 20, 30, 10, 20, 30

Operations [0 1 2 0 2 1] on [5 5 5 5 5 5]:
Results: [ 5 10 25  5 25 10]
(0=keep, 1=double, 2=square)

💡 np.choose() picks values from different arrays based on indices!


---
# 🔗 Part 12: Array Manipulation (Stack, Split, Concatenate)

Combining and splitting arrays in various ways!

In [56]:
# Concatenate - join arrays end-to-end

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# Concatenate 1D arrays
combined = np.concatenate([arr1, arr2, arr3])
print("Three arrays combined:", combined)

# Concatenate 2D arrays vertically (stack rows)
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

vertical = np.concatenate([matrix1, matrix2], axis=0)
print("\nVertical concatenation (axis=0):")
print(vertical)

# Concatenate horizontally (stack columns)
horizontal = np.concatenate([matrix1, matrix2], axis=1)
print("\nHorizontal concatenation (axis=1):")
print(horizontal)

print("\n💡 axis=0 stacks vertically, axis=1 stacks horizontally!")

Three arrays combined: [1 2 3 4 5 6 7 8 9]

Vertical concatenation (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal concatenation (axis=1):
[[1 2 5 6]
 [3 4 7 8]]

💡 axis=0 stacks vertically, axis=1 stacks horizontally!


In [57]:
# Stack functions - convenient ways to combine arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# vstack - vertical stack (rows)
vstacked = np.vstack([arr1, arr2])
print("vstack (vertical):")
print(vstacked)

# hstack - horizontal stack (columns)
hstacked = np.hstack([arr1, arr2])
print("\nhstack (horizontal):")
print(hstacked)

# dstack - depth stack (3D)
dstacked = np.dstack([arr1, arr2])
print("\ndstack (depth):")
print(dstacked)
print(f"Shape: {dstacked.shape}")

# column_stack - make columns
col_stacked = np.column_stack([arr1, arr2])
print("\ncolumn_stack:")
print(col_stacked)

# row_stack - make rows (same as vstack)
row_stacked = np.row_stack([arr1, arr2])
print("\nrow_stack:")
print(row_stacked)

print("\n💡 vstack/hstack/dstack are shortcuts for common concatenations!")

vstack (vertical):
[[1 2 3]
 [4 5 6]]

hstack (horizontal):
[1 2 3 4 5 6]

dstack (depth):
[[[1 4]
  [2 5]
  [3 6]]]
Shape: (1, 3, 2)

column_stack:
[[1 4]
 [2 5]
 [3 6]]

row_stack:
[[1 2 3]
 [4 5 6]]

💡 vstack/hstack/dstack are shortcuts for common concatenations!


In [58]:
# Splitting arrays - opposite of concatenation

arr = np.arange(12)
print("Original array:", arr)

# Split into 3 equal parts
split_3 = np.split(arr, 3)
print("\nSplit into 3 parts:")
for i, part in enumerate(split_3):
    print(f"  Part {i+1}: {part}")

# Split at specific indices
split_at = np.split(arr, [3, 7])
print("\nSplit at indices [3, 7]:")
for i, part in enumerate(split_at):
    print(f"  Part {i+1}: {part}")

# Split 2D array
matrix = np.arange(16).reshape(4, 4)
print("\nOriginal matrix:")
print(matrix)

# Split vertically (into rows)
vsplit_result = np.vsplit(matrix, 2)
print("\nVertical split (2 parts):")
for i, part in enumerate(vsplit_result):
    print(f"Part {i+1}:")
    print(part)

# Split horizontally (into columns)
hsplit_result = np.hsplit(matrix, 2)
print("\nHorizontal split (2 parts):")
for i, part in enumerate(hsplit_result):
    print(f"Part {i+1}:")
    print(part)

print("\n💡 split/vsplit/hsplit divide arrays into pieces!")

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Split into 3 parts:
  Part 1: [0 1 2 3]
  Part 2: [4 5 6 7]
  Part 3: [ 8  9 10 11]

Split at indices [3, 7]:
  Part 1: [0 1 2]
  Part 2: [3 4 5 6]
  Part 3: [ 7  8  9 10 11]

Original matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Vertical split (2 parts):
Part 1:
[[0 1 2 3]
 [4 5 6 7]]
Part 2:
[[ 8  9 10 11]
 [12 13 14 15]]

Horizontal split (2 parts):
Part 1:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

💡 split/vsplit/hsplit divide arrays into pieces!


In [59]:
# Repeat and tile - duplicate arrays

arr = np.array([1, 2, 3])
print("Original:", arr)

# Repeat each element
repeated = np.repeat(arr, 3)
print("\nRepeat each element 3 times:", repeated)

# Repeat with different counts
repeated_diff = np.repeat(arr, [1, 2, 3])
print("Repeat [1,2,3] times:", repeated_diff)

# Tile - repeat entire array
tiled = np.tile(arr, 3)
print("\nTile array 3 times:", tiled)

# Tile in 2D
tiled_2d = np.tile(arr, (2, 3))
print("\nTile in 2D (2 rows, 3 times):")
print(tiled_2d)

print("\n💡 repeat() duplicates elements, tile() duplicates whole array!")

Original: [1 2 3]

Repeat each element 3 times: [1 1 1 2 2 2 3 3 3]
Repeat [1,2,3] times: [1 2 2 3 3 3]

Tile array 3 times: [1 2 3 1 2 3 1 2 3]

Tile in 2D (2 rows, 3 times):
[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]

💡 repeat() duplicates elements, tile() duplicates whole array!


---
# 🎪 Part 13: Set Operations

Working with unique values and set operations!

In [60]:
# Finding unique values

arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5])
print("Original array:", arr)

# Get unique values
unique_vals = np.unique(arr)
print("Unique values:", unique_vals)

# Get unique values with counts
unique_vals, counts = np.unique(arr, return_counts=True)
print("\nUnique values with counts:")
for val, count in zip(unique_vals, counts):
    print(f"  {val} appears {count} times")

# Get indices of first occurrence
unique_vals, indices = np.unique(arr, return_index=True)
print(f"\nFirst occurrence indices: {indices}")

# Get inverse indices (reconstruct original from unique)
unique_vals, inverse = np.unique(arr, return_inverse=True)
print(f"\nInverse indices: {inverse}")
print(f"Reconstructed: {unique_vals[inverse]}")

print("\n💡 np.unique() finds distinct values and their properties!")

Original array: [1 2 2 3 3 3 4 4 4 4 5]
Unique values: [1 2 3 4 5]

Unique values with counts:
  1 appears 1 times
  2 appears 2 times
  3 appears 3 times
  4 appears 4 times
  5 appears 1 times

First occurrence indices: [ 0  1  3  6 10]

Inverse indices: [0 1 1 2 2 2 3 3 3 3 4]
Reconstructed: [1 2 2 3 3 3 4 4 4 4 5]

💡 np.unique() finds distinct values and their properties!


In [61]:
# Set operations between arrays

set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([4, 5, 6, 7, 8])

print("Set 1:", set1)
print("Set 2:", set2)

# Union (all unique values from both)
union = np.union1d(set1, set2)
print("\nUnion (all values):", union)

# Intersection (common values)
intersection = np.intersect1d(set1, set2)
print("Intersection (common):", intersection)

# Difference (in set1 but not set2)
difference = np.setdiff1d(set1, set2)
print("Difference (set1 - set2):", difference)

# Symmetric difference (in either but not both)
sym_diff = np.setxor1d(set1, set2)
print("Symmetric difference:", sym_diff)

# Check membership
is_member = np.in1d(set1, set2)
print(f"\nWhich of set1 are in set2? {is_member}")
print(f"Values: {set1[is_member]}")

print("\n💡 NumPy has all standard set operations!")

Set 1: [1 2 3 4 5]
Set 2: [4 5 6 7 8]

Union (all values): [1 2 3 4 5 6 7 8]
Intersection (common): [4 5]
Difference (set1 - set2): [1 2 3]
Symmetric difference: [1 2 3 6 7 8]

Which of set1 are in set2? [False False False  True  True]
Values: [4 5]

💡 NumPy has all standard set operations!


---
# 💾 Part 14: File I/O (Saving and Loading)

Save your arrays to disk and load them later!

In [62]:
# Saving and loading binary files (.npy)

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original data:")
print(data)

# Save to binary file
np.save('my_array.npy', data)
print("\n✅ Saved to 'my_array.npy'")

# Load from binary file
loaded = np.load('my_array.npy')
print("\nLoaded data:")
print(loaded)

# Save multiple arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.savez('multiple_arrays.npz', first=arr1, second=arr2)
print("\n✅ Saved multiple arrays to 'multiple_arrays.npz'")

# Load multiple arrays
loaded_data = np.load('multiple_arrays.npz')
print("\nLoaded arrays:")
print("First:", loaded_data['first'])
print("Second:", loaded_data['second'])

# Compressed save (for large arrays)
large_array = np.random.rand(1000, 1000)
np.savez_compressed('compressed.npz', data=large_array)
print("\n✅ Saved compressed array")

print("\n💡 .npy for single arrays, .npz for multiple arrays!")

Original data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

✅ Saved to 'my_array.npy'

Loaded data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

✅ Saved multiple arrays to 'multiple_arrays.npz'

Loaded arrays:
First: [1 2 3]
Second: [4 5 6]

✅ Saved compressed array

💡 .npy for single arrays, .npz for multiple arrays!


In [63]:
# Saving and loading text files (.txt, .csv)

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Save as text file
np.savetxt('data.txt', data)
print("✅ Saved to 'data.txt'")

# Save as CSV
np.savetxt('data.csv', data, delimiter=',', fmt='%d')
print("✅ Saved to 'data.csv'")

# Save with header and formatting
np.savetxt('data_formatted.csv', data, delimiter=',', 
           header='Col1,Col2,Col3', comments='', fmt='%.2f')
print("✅ Saved formatted CSV")

# Load from text file
loaded_txt = np.loadtxt('data.txt')
print("\nLoaded from text:")
print(loaded_txt)

# Load from CSV
loaded_csv = np.loadtxt('data.csv', delimiter=',')
print("\nLoaded from CSV:")
print(loaded_csv)

# Load with specific data type
loaded_int = np.loadtxt('data.csv', delimiter=',', dtype=int)
print("\nLoaded as integers:")
print(loaded_int)

print("\n💡 Text files are human-readable but larger than binary!")

✅ Saved to 'data.txt'
✅ Saved to 'data.csv'
✅ Saved formatted CSV

Loaded from text:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Loaded from CSV:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Loaded as integers:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

💡 Text files are human-readable but larger than binary!


In [64]:
# genfromtxt - advanced text loading (handles missing data)

# Create a CSV with missing values
csv_content = """1,2,3
4,,6
7,8,"""

with open('data_missing.csv', 'w') as f:
    f.write(csv_content)

# Load with missing values
data_with_missing = np.genfromtxt('data_missing.csv', delimiter=',')
print("Data with missing values (nan):")
print(data_with_missing)

# Fill missing values
data_filled = np.genfromtxt('data_missing.csv', delimiter=',', filling_values=0)
print("\nMissing values filled with 0:")
print(data_filled)

# Skip header row
csv_with_header = """Name,Age,Score
Alice,25,85
Bob,30,92"""

with open('data_header.csv', 'w') as f:
    f.write(csv_with_header)

data_skip_header = np.genfromtxt('data_header.csv', delimiter=',', 
                                  skip_header=1, dtype=None, encoding=None)
print("\nData with header skipped:")
print(data_skip_header)

print("\n💡 genfromtxt() is powerful for messy real-world data!")

Data with missing values (nan):
[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8. nan]]

Missing values filled with 0:
[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 0.]]

Data with header skipped:
[('Alice', 25, 85) ('Bob', 30, 92)]

💡 genfromtxt() is powerful for messy real-world data!


---
# ⚡ Part 15: Universal Functions (ufuncs)

Fast element-wise operations that work on entire arrays!

In [65]:
# Mathematical ufuncs

arr = np.array([1, 4, 9, 16, 25])
print("Original:", arr)

# Square root
print("Square root:", np.sqrt(arr))

# Exponential
print("Exponential:", np.exp(np.array([1, 2, 3])))

# Logarithms
print("Natural log:", np.log(arr))
print("Log base 10:", np.log10(arr))
print("Log base 2:", np.log2(arr))

# Power
print("Power of 2:", np.power(arr, 2))

# Absolute value
negatives = np.array([-1, -2, 3, -4, 5])
print(f"\nAbsolute of {negatives}:", np.abs(negatives))

# Sign
print("Sign (-1, 0, or 1):", np.sign(negatives))

print("\n💡 Ufuncs are optimized and much faster than Python loops!")

Original: [ 1  4  9 16 25]
Square root: [1. 2. 3. 4. 5.]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Log base 10: [0.         0.60205999 0.95424251 1.20411998 1.39794001]
Log base 2: [0.         2.         3.169925   4.         4.64385619]
Power of 2: [  1  16  81 256 625]

Absolute of [-1 -2  3 -4  5]: [1 2 3 4 5]
Sign (-1, 0, or 1): [-1 -1  1 -1  1]

💡 Ufuncs are optimized and much faster than Python loops!


In [66]:
# Trigonometric ufuncs

angles_deg = np.array([0, 30, 45, 60, 90])
angles_rad = np.deg2rad(angles_deg)

print("Angles (degrees):", angles_deg)
print("Angles (radians):", angles_rad.round(3))

# Trig functions (work with radians)
print("\nSine:", np.sin(angles_rad).round(3))
print("Cosine:", np.cos(angles_rad).round(3))
print("Tangent:", np.tan(angles_rad).round(3))

# Inverse trig functions
values = np.array([0, 0.5, 0.707, 0.866, 1])
print("\nArcsin (radians):", np.arcsin(values).round(3))
print("Arcsin (degrees):", np.rad2deg(np.arcsin(values)).round(1))

# Hyperbolic functions
print("\nSinh:", np.sinh(np.array([0, 1, 2])).round(3))
print("Cosh:", np.cosh(np.array([0, 1, 2])).round(3))

print("\n💡 All trig functions work element-wise on arrays!")

Angles (degrees): [ 0 30 45 60 90]
Angles (radians): [0.    0.524 0.785 1.047 1.571]

Sine: [0.    0.5   0.707 0.866 1.   ]
Cosine: [1.    0.866 0.707 0.5   0.   ]
Tangent: [0.00000000e+00 5.77000000e-01 1.00000000e+00 1.73200000e+00
 1.63312394e+16]

Arcsin (radians): [0.    0.524 0.785 1.047 1.571]
Arcsin (degrees): [ 0. 30. 45. 60. 90.]

Sinh: [0.    1.175 3.627]
Cosh: [1.    1.543 3.762]

💡 All trig functions work element-wise on arrays!


In [67]:
# Rounding ufuncs

arr = np.array([1.23, 2.67, 3.14, 4.89, 5.50])
print("Original:", arr)

# Round to nearest integer
print("Round:", np.round(arr))

# Round to decimal places
print("Round to 1 decimal:", np.round(arr, 1))

# Floor (round down)
print("Floor:", np.floor(arr))

# Ceiling (round up)
print("Ceil:", np.ceil(arr))

# Truncate (remove decimals)
print("Trunc:", np.trunc(arr))

# Clip values to range
clipped = np.clip(arr, 2, 4)
print(f"\nClip to [2, 4]: {clipped}")
print("(Values below 2 become 2, above 4 become 4)")

print("\n💡 Different rounding modes for different needs!")

Original: [1.23 2.67 3.14 4.89 5.5 ]
Round: [1. 3. 3. 5. 6.]
Round to 1 decimal: [1.2 2.7 3.1 4.9 5.5]
Floor: [1. 2. 3. 4. 5.]
Ceil: [2. 3. 4. 5. 6.]
Trunc: [1. 2. 3. 4. 5.]

Clip to [2, 4]: [2.   2.67 3.14 4.   4.  ]
(Values below 2 become 2, above 4 become 4)

💡 Different rounding modes for different needs!


In [68]:
# Comparison and logical ufuncs

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

print("Array 1:", arr1)
print("Array 2:", arr2)

# Element-wise maximum
print("\nMaximum of each pair:", np.maximum(arr1, arr2))

# Element-wise minimum
print("Minimum of each pair:", np.minimum(arr1, arr2))

# Logical operations
bool1 = np.array([True, True, False, False])
bool2 = np.array([True, False, True, False])

print("\nBool 1:", bool1)
print("Bool 2:", bool2)
print("AND:", np.logical_and(bool1, bool2))
print("OR:", np.logical_or(bool1, bool2))
print("XOR:", np.logical_xor(bool1, bool2))
print("NOT bool1:", np.logical_not(bool1))

# Greater/less comparisons
print(f"\narr1 > arr2: {np.greater(arr1, arr2)}")
print(f"arr1 >= 3: {np.greater_equal(arr1, 3)}")

print("\n💡 Ufuncs work element-wise, even for comparisons!")

Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]

Maximum of each pair: [5 4 3 4 5]
Minimum of each pair: [1 2 3 2 1]

Bool 1: [ True  True False False]
Bool 2: [ True False  True False]
AND: [ True False False False]
OR: [ True  True  True False]
XOR: [False  True  True False]
NOT bool1: [False False  True  True]

arr1 > arr2: [False False False  True  True]
arr1 >= 3: [False False  True  True  True]

💡 Ufuncs work element-wise, even for comparisons!


---
# 📊 Part 16: Advanced Statistical Functions

Beyond basic mean and median - comprehensive statistical analysis!

In [69]:
# Percentiles and quantiles

data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Data:", data)

# Percentiles
p25 = np.percentile(data, 25)
p50 = np.percentile(data, 50)
p75 = np.percentile(data, 75)

print(f"\n25th percentile: {p25}")
print(f"50th percentile (median): {p50}")
print(f"75th percentile: {p75}")

# Multiple percentiles at once
percentiles = np.percentile(data, [10, 25, 50, 75, 90])
print(f"\nMultiple percentiles [10,25,50,75,90]: {percentiles}")

# Quantiles (0 to 1 instead of 0 to 100)
quartiles = np.quantile(data, [0.25, 0.5, 0.75])
print(f"Quartiles: {quartiles}")

print("\n💡 Percentiles divide data into 100 parts, quantiles use 0-1 scale!")

Data: [ 10  20  30  40  50  60  70  80  90 100]

25th percentile: 32.5
50th percentile (median): 55.0
75th percentile: 77.5

Multiple percentiles [10,25,50,75,90]: [19.  32.5 55.  77.5 91. ]
Quartiles: [32.5 55.  77.5]

💡 Percentiles divide data into 100 parts, quantiles use 0-1 scale!


In [70]:
# Variance and correlation

data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([2, 4, 6, 8, 10])
data3 = np.array([5, 4, 3, 2, 1])

print("Data 1:", data1)
print("Data 2:", data2)
print("Data 3:", data3)

# Variance (how spread out the data is)
var1 = np.var(data1)
print(f"\nVariance of data1: {var1}")

# Standard deviation (square root of variance)
std1 = np.std(data1)
print(f"Std deviation of data1: {std1:.3f}")

# Covariance matrix (how variables change together)
cov_matrix = np.cov([data1, data2, data3])
print("\nCovariance matrix:")
print(cov_matrix)

# Correlation coefficient (-1 to 1)
corr_matrix = np.corrcoef([data1, data2, data3])
print("\nCorrelation matrix:")
print(corr_matrix.round(3))
print("\n💡 1 = perfect positive correlation")
print("💡 -1 = perfect negative correlation")
print("💡 0 = no correlation")

Data 1: [1 2 3 4 5]
Data 2: [ 2  4  6  8 10]
Data 3: [5 4 3 2 1]

Variance of data1: 2.0
Std deviation of data1: 1.414

Covariance matrix:
[[ 2.5  5.  -2.5]
 [ 5.  10.  -5. ]
 [-2.5 -5.   2.5]]

Correlation matrix:
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]]

💡 1 = perfect positive correlation
💡 -1 = perfect negative correlation
💡 0 = no correlation


In [71]:
# Histogram and binning

data = np.random.randn(1000) * 10 + 50
print(f"Generated {len(data)} random values")
print(f"Mean: {np.mean(data):.2f}, Std: {np.std(data):.2f}")

# Create histogram
counts, bin_edges = np.histogram(data, bins=10)
print(f"\nHistogram (10 bins):")
print(f"Bin edges: {bin_edges.round(1)}")
print(f"Counts: {counts}")

# Custom bin edges
custom_bins = [0, 30, 40, 50, 60, 70, 100]
counts, edges = np.histogram(data, bins=custom_bins)
print(f"\nCustom bins: {custom_bins}")
print(f"Counts: {counts}")

# Digitize - find which bin each value belongs to
bins = [0, 25, 50, 75, 100]
indices = np.digitize(data[:10], bins)
print(f"\nFirst 10 values: {data[:10].round(1)}")
print(f"Bin indices: {indices}")

print("\n💡 Histograms group data into bins for analysis!")

Generated 1000 random values
Mean: 49.87, Std: 9.84

Histogram (10 bins):
Bin edges: [22.7 28.9 35.2 41.4 47.7 53.9 60.2 66.4 72.7 78.9 85.2]
Counts: [ 10  52 125 238 253 164 103  39  13   3]

Custom bins: [0, 30, 40, 50, 60, 70, 100]
Counts: [ 14 137 389 299 138  23]

First 10 values: [76.6 39.7 71.6 53.6 57.5 60.2 54.3 25.8 32.8 23.5]
Bin indices: [4 2 3 3 3 3 3 2 2 1]

💡 Histograms group data into bins for analysis!


In [72]:
# Cumulative operations

arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Cumulative sum
cumsum = np.cumsum(arr)
print("\nCumulative sum:", cumsum)
print("(1, 1+2, 1+2+3, 1+2+3+4, 1+2+3+4+5)")

# Cumulative product
cumprod = np.cumprod(arr)
print("\nCumulative product:", cumprod)
print("(1, 1×2, 1×2×3, 1×2×3×4, 1×2×3×4×5)")

# Differences between consecutive elements
diff = np.diff(arr)
print("\nDifferences:", diff)
print("(2-1, 3-2, 4-3, 5-4)")

# 2D cumulative sum
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrix:")
print(matrix)
print("\nCumulative sum along axis 0:")
print(np.cumsum(matrix, axis=0))
print("\nCumulative sum along axis 1:")
print(np.cumsum(matrix, axis=1))

print("\n💡 Cumulative operations build up values progressively!")

Array: [1 2 3 4 5]

Cumulative sum: [ 1  3  6 10 15]
(1, 1+2, 1+2+3, 1+2+3+4, 1+2+3+4+5)

Cumulative product: [  1   2   6  24 120]
(1, 1×2, 1×2×3, 1×2×3×4, 1×2×3×4×5)

Differences: [1 1 1 1]
(2-1, 3-2, 4-3, 5-4)

Matrix:
[[1 2 3]
 [4 5 6]]

Cumulative sum along axis 0:
[[1 2 3]
 [5 7 9]]

Cumulative sum along axis 1:
[[ 1  3  6]
 [ 4  9 15]]

💡 Cumulative operations build up values progressively!


---
# 📐 Part 17: Polynomial and Mathematical Functions

Working with polynomials and advanced math!

In [73]:
# Polynomial operations

# Polynomial: 2x² + 3x + 1
# Coefficients from highest to lowest degree
poly = np.poly1d([2, 3, 1])
print("Polynomial: 2x² + 3x + 1")
print(poly)

# Evaluate polynomial at specific points
x_values = np.array([0, 1, 2, 3])
y_values = poly(x_values)
print(f"\nEvaluate at x = {x_values}:")
print(f"Results: {y_values}")

# Find roots (where polynomial = 0)
roots = np.roots([2, 3, 1])
print(f"\nRoots (where y=0): {roots}")

# Polynomial from roots
# Create polynomial with roots at 1 and 2
poly_from_roots = np.poly1d([1, -1]) * np.poly1d([1, -2])
print(f"\nPolynomial with roots at 1 and 2:")
print(poly_from_roots)

print("\n💡 NumPy can create, evaluate, and solve polynomials!")

Polynomial: 2x² + 3x + 1
   2
2 x + 3 x + 1

Evaluate at x = [0 1 2 3]:
Results: [ 1  6 15 28]

Roots (where y=0): [-1.  -0.5]

Polynomial with roots at 1 and 2:
   2
1 x - 3 x + 2

💡 NumPy can create, evaluate, and solve polynomials!


In [74]:
# Polynomial fitting (find best-fit polynomial for data)

# Generate some noisy data
x = np.linspace(0, 10, 20)
y_true = 2*x**2 + 3*x + 1
y_noisy = y_true + np.random.randn(20) * 10

print("Fitting polynomial to noisy data...")

# Fit a 2nd degree polynomial
coefficients = np.polyfit(x, y_noisy, 2)
print(f"\nFitted coefficients: {coefficients}")
print(f"Original: [2, 3, 1]")

# Create polynomial from fitted coefficients
fitted_poly = np.poly1d(coefficients)
y_fitted = fitted_poly(x)

print(f"\nOriginal equation: 2x² + 3x + 1")
print(f"Fitted equation: {fitted_poly}")

# Evaluate fit quality
residuals = y_noisy - y_fitted
rmse = np.sqrt(np.mean(residuals**2))
print(f"\nRoot Mean Square Error: {rmse:.2f}")

print("\n💡 polyfit() finds the best polynomial to match your data!")

Fitting polynomial to noisy data...

Fitted coefficients: [1.87213024 4.09518572 1.84517632]
Original: [2, 3, 1]

Original equation: 2x² + 3x + 1
Fitted equation:        2
1.872 x + 4.095 x + 1.845

Root Mean Square Error: 9.89

💡 polyfit() finds the best polynomial to match your data!


In [75]:
# Derivatives and integrals of polynomials

poly = np.poly1d([2, 3, 1])
print("Original polynomial: 2x² + 3x + 1")
print(poly)

# Derivative (slope)
derivative = np.polyder(poly)
print("\nDerivative: 4x + 3")
print(derivative)

# Second derivative
second_deriv = np.polyder(poly, 2)
print("\nSecond derivative: 4")
print(second_deriv)

# Integral (antiderivative)
integral = np.polyint(poly)
print("\nIntegral: (2/3)x³ + (3/2)x² + x + C")
print(integral)

# Evaluate derivative at specific points
x = np.array([0, 1, 2])
print(f"\nDerivative at x={x}: {derivative(x)}")

print("\n💡 polyder() differentiates, polyint() integrates!")

Original polynomial: 2x² + 3x + 1
   2
2 x + 3 x + 1

Derivative: 4x + 3
 
4 x + 3

Second derivative: 4
 
4

Integral: (2/3)x³ + (3/2)x² + x + C
        3       2
0.6667 x + 1.5 x + 1 x

Derivative at x=[0 1 2]: [ 3  7 11]

💡 polyder() differentiates, polyint() integrates!


In [76]:
# Numerical integration and differentiation

# Trapezoidal integration
x = np.linspace(0, np.pi, 100)
y = np.sin(x)

# Integrate sin(x) from 0 to π (should be ~2)
integral = np.trapz(y, x)
print(f"Integral of sin(x) from 0 to π: {integral:.4f}")
print("(Exact value: 2.0)")

# Gradient (numerical derivative)
x = np.linspace(0, 2*np.pi, 50)
y = np.sin(x)
dy_dx = np.gradient(y, x)

print(f"\nAt x=0: sin(0)={y[0]:.3f}, derivative={dy_dx[0]:.3f}")
print(f"At x=π/2: sin(π/2)={y[12]:.3f}, derivative={dy_dx[12]:.3f}")
print("(Derivative of sin is cos)")

# 2D gradient
matrix = np.array([[1, 2, 4], [3, 5, 8], [6, 9, 12]])
grad_y, grad_x = np.gradient(matrix)
print("\nMatrix:")
print(matrix)
print("\nGradient in y direction:")
print(grad_y)
print("\nGradient in x direction:")
print(grad_x)

print("\n💡 trapz() integrates, gradient() differentiates numerically!")

Integral of sin(x) from 0 to π: 1.9998
(Exact value: 2.0)

At x=0: sin(0)=0.000, derivative=0.997
At x=π/2: sin(π/2)=0.999, derivative=0.032
(Derivative of sin is cos)

Matrix:
[[ 1  2  4]
 [ 3  5  8]
 [ 6  9 12]]

Gradient in y direction:
[[2.  3.  4. ]
 [2.5 3.5 4. ]
 [3.  4.  4. ]]

Gradient in x direction:
[[1.  1.5 2. ]
 [2.  2.5 3. ]
 [3.  3.  3. ]]

💡 trapz() integrates, gradient() differentiates numerically!


---
# 🏗️ Part 18: Structured Arrays (Like Mini-Databases)

Arrays with named fields - perfect for tabular data!

In [77]:
# Creating structured arrays

# Define data type with field names
dt = np.dtype([('name', 'U20'), ('age', 'i4'), ('score', 'f8')])

# Create structured array
students = np.array([
    ('Alice', 25, 85.5),
    ('Bob', 30, 92.0),
    ('Charlie', 22, 78.5),
    ('Diana', 28, 95.0)
], dtype=dt)

print("Structured array:")
print(students)

# Access by field name
print("\nAll names:", students['name'])
print("All ages:", students['age'])
print("All scores:", students['score'])

# Access individual record
print(f"\nFirst student: {students[0]}")
print(f"Bob's score: {students[1]['score']}")

# Filter by condition
high_scorers = students[students['score'] > 85]
print("\nHigh scorers (>85):")
print(high_scorers)

print("\n💡 Structured arrays combine the power of arrays with named fields!")

Structured array:
[('Alice', 25, 85.5) ('Bob', 30, 92. ) ('Charlie', 22, 78.5)
 ('Diana', 28, 95. )]

All names: ['Alice' 'Bob' 'Charlie' 'Diana']
All ages: [25 30 22 28]
All scores: [85.5 92.  78.5 95. ]

First student: ('Alice', 25, 85.5)
Bob's score: 92.0

High scorers (>85):
[('Alice', 25, 85.5) ('Bob', 30, 92. ) ('Diana', 28, 95. )]

💡 Structured arrays combine the power of arrays with named fields!


In [78]:
# Record arrays (easier field access)

# Create record array
students_rec = np.rec.array([
    ('Alice', 25, 85.5),
    ('Bob', 30, 92.0),
    ('Charlie', 22, 78.5)
], dtype=[('name', 'U20'), ('age', 'i4'), ('score', 'f8')])

print("Record array:")
print(students_rec)

# Access fields as attributes (easier!)
print("\nNames:", students_rec.name)
print("Ages:", students_rec.age)
print("Scores:", students_rec.score)

# Modify values
students_rec.score[0] = 90.0
print(f"\nAlice's new score: {students_rec.score[0]}")

# Statistics on fields
print(f"\nAverage age: {students_rec.age.mean()}")
print(f"Average score: {students_rec.score.mean():.2f}")
print(f"Max score: {students_rec.score.max()}")

print("\n💡 Record arrays let you use dot notation for fields!")

Record array:
[('Alice', 25, 85.5) ('Bob', 30, 92. ) ('Charlie', 22, 78.5)]

Names: ['Alice' 'Bob' 'Charlie']
Ages: [25 30 22]
Scores: [85.5 92.  78.5]

Alice's new score: 90.0

Average age: 25.666666666666668
Average score: 86.83
Max score: 92.0

💡 Record arrays let you use dot notation for fields!


In [79]:
# Nested structured arrays

# Define nested structure
dt = np.dtype([
    ('name', 'U20'),
    ('age', 'i4'),
    ('grades', [('math', 'f8'), ('science', 'f8'), ('english', 'f8')])
])

students = np.array([
    ('Alice', 25, (85, 90, 88)),
    ('Bob', 30, (92, 88, 95)),
    ('Charlie', 22, (78, 85, 82))
], dtype=dt)

print("Nested structured array:")
print(students)

# Access nested fields
print("\nAll math grades:", students['grades']['math'])
print("All science grades:", students['grades']['science'])

# Access individual nested field
print(f"\nAlice's math grade: {students[0]['grades']['math']}")

# Calculate average per student
for student in students:
    grades = [student['grades']['math'], 
              student['grades']['science'], 
              student['grades']['english']]
    avg = np.mean(grades)
    print(f"{student['name']}: avg = {avg:.2f}")

print("\n💡 Nested structures organize complex data hierarchically!")

Nested structured array:
[('Alice', 25, (85., 90., 88.)) ('Bob', 30, (92., 88., 95.))
 ('Charlie', 22, (78., 85., 82.))]

All math grades: [85. 92. 78.]
All science grades: [90. 88. 85.]

Alice's math grade: 85.0
Alice: avg = 87.67
Bob: avg = 91.67
Charlie: avg = 81.67

💡 Nested structures organize complex data hierarchically!


---
# ⚡ Part 19: Memory and Performance

Understanding views vs copies and optimizing performance!

In [80]:
# Views vs Copies - IMPORTANT!

original = np.array([1, 2, 3, 4, 5])
print("Original:", original)

# Slicing creates a VIEW (shares memory)
view = original[1:4]
print("View (slice):", view)

# Modify the view
view[0] = 999
print("\nAfter modifying view:")
print("View:", view)
print("Original:", original)
print("⚠️  Original changed too! They share memory!")

# Create a COPY (independent)
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()
copy[0] = 999
print("\nWith .copy():")
print("Copy:", copy)
print("Original:", original)
print("✅ Original unchanged! Independent memory!")

# Check if it's a view or copy
print(f"\nIs view a view? {view.base is not None}")
print(f"Is copy a view? {copy.base is None}")

print("\n💡 Slicing creates views (fast, shared memory)")
print("💡 Use .copy() for independent arrays!")

Original: [1 2 3 4 5]
View (slice): [2 3 4]

After modifying view:
View: [999   3   4]
Original: [  1 999   3   4   5]
⚠️  Original changed too! They share memory!

With .copy():
Copy: [999   3   4]
Original: [1 2 3 4 5]
✅ Original unchanged! Independent memory!

Is view a view? True
Is copy a view? True

💡 Slicing creates views (fast, shared memory)
💡 Use .copy() for independent arrays!


In [81]:
# Memory layout: C-order vs Fortran-order

# C-order (row-major, default)
c_array = np.array([[1, 2, 3], [4, 5, 6]], order='C')
print("C-order (row-major):")
print(c_array)
print(f"Flags: C_CONTIGUOUS={c_array.flags['C_CONTIGUOUS']}")
print("Memory: [1,2,3,4,5,6] - rows stored together")

# Fortran-order (column-major)
f_array = np.array([[1, 2, 3], [4, 5, 6]], order='F')
print("\nFortran-order (column-major):")
print(f_array)
print(f"Flags: F_CONTIGUOUS={f_array.flags['F_CONTIGUOUS']}")
print("Memory: [1,4,2,5,3,6] - columns stored together")

# Performance difference
import time

large = np.random.rand(1000, 1000)

# Sum by rows (fast for C-order)
start = time.time()
for i in range(1000):
    _ = large[i, :].sum()
row_time = time.time() - start

# Sum by columns (slower for C-order)
start = time.time()
for i in range(1000):
    _ = large[:, i].sum()
col_time = time.time() - start

print(f"\nRow operations: {row_time:.4f}s")
print(f"Column operations: {col_time:.4f}s")
print("💡 Access patterns matching memory layout are faster!")

C-order (row-major):
[[1 2 3]
 [4 5 6]]
Flags: C_CONTIGUOUS=True
Memory: [1,2,3,4,5,6] - rows stored together

Fortran-order (column-major):
[[1 2 3]
 [4 5 6]]
Flags: F_CONTIGUOUS=True
Memory: [1,4,2,5,3,6] - columns stored together

Row operations: 0.0009s
Column operations: 0.0012s
💡 Access patterns matching memory layout are faster!


In [82]:
# Vectorization for performance

import time

# Bad: Python loop
def slow_sum(arr):
    total = 0
    for i in range(len(arr)):
        total += arr[i]
    return total

# Good: NumPy vectorized
def fast_sum(arr):
    return np.sum(arr)

# Test performance
large_array = np.random.rand(1000000)

start = time.time()
result1 = slow_sum(large_array)
slow_time = time.time() - start

start = time.time()
result2 = fast_sum(large_array)
fast_time = time.time() - start

print(f"Python loop: {slow_time:.4f}s")
print(f"NumPy vectorized: {fast_time:.4f}s")
print(f"Speedup: {slow_time/fast_time:.1f}x faster!")

# Vectorized operations example
arr = np.arange(1000000)

# Bad: loop
start = time.time()
result = np.zeros(len(arr))
for i in range(len(arr)):
    result[i] = arr[i] ** 2 + 2 * arr[i] + 1
loop_time = time.time() - start

# Good: vectorized
start = time.time()
result = arr**2 + 2*arr + 1
vec_time = time.time() - start

print(f"\nLoop: {loop_time:.4f}s")
print(f"Vectorized: {vec_time:.4f}s")
print(f"Speedup: {loop_time/vec_time:.1f}x faster!")

print("\n💡 Always use vectorized operations instead of loops!")

Python loop: 0.0645s
NumPy vectorized: 0.0004s
Speedup: 173.0x faster!

Loop: 0.3062s
Vectorized: 0.0042s
Speedup: 73.0x faster!

💡 Always use vectorized operations instead of loops!


In [83]:
# Memory-efficient operations

# Pre-allocate arrays instead of growing them
n = 100000

# Bad: growing array
start = time.time()
bad_array = np.array([])
for i in range(1000):
    bad_array = np.append(bad_array, i)
bad_time = time.time() - start

# Good: pre-allocate
start = time.time()
good_array = np.zeros(1000)
for i in range(1000):
    good_array[i] = i
good_time = time.time() - start

print(f"Growing array: {bad_time:.4f}s")
print(f"Pre-allocated: {good_time:.4f}s")
print(f"Speedup: {bad_time/good_time:.1f}x faster!")

# In-place operations save memory
arr = np.random.rand(1000, 1000)

# Creates new array (uses more memory)
result1 = arr * 2

# In-place (modifies existing, saves memory)
arr *= 2

print("\n💡 Pre-allocate arrays and use in-place operations!")
print("💡 arr *= 2 is better than arr = arr * 2")

Growing array: 0.0019s
Pre-allocated: 0.0001s
Speedup: 20.2x faster!

💡 Pre-allocate arrays and use in-place operations!
💡 arr *= 2 is better than arr = arr * 2


---
# 🌟 Part 20: Real-World Examples

Practical applications putting it all together!

In [84]:
# Example 1: Image Processing (grayscale image manipulation)

# Simulate a grayscale image (8x8 pixels, values 0-255)
image = np.random.randint(0, 256, size=(8, 8), dtype=np.uint8)
print("Original image (8x8 pixels):")
print(image)

# Increase brightness (add 50 to all pixels, clip to 255)
brighter = np.clip(image + 50, 0, 255).astype(np.uint8)
print("\nBrighter image:")
print(brighter)

# Decrease contrast (compress values toward middle)
contrast_reduced = ((image - 128) * 0.5 + 128).astype(np.uint8)
print("\nReduced contrast:")
print(contrast_reduced)

# Invert colors
inverted = 255 - image
print("\nInverted:")
print(inverted)

# Threshold (binary: black or white)
threshold = 128
binary = np.where(image > threshold, 255, 0).astype(np.uint8)
print(f"\nBinary (threshold={threshold}):")
print(binary)

print("\n💡 NumPy makes image processing fast and easy!")

Original image (8x8 pixels):
[[  6 121 191 105 232  39  68 253]
 [241 146  58 130 206 228  47 159]
 [ 44 113 109 100  48 117 113 229]
 [229  31  37  71 120  83 108 140]
 [123 168  36 224 135   1 139  73]
 [208 228 221 170  37  70 194  50]
 [116  50 103 160 248 102  64 152]
 [131 184 243  93 103 214 136 231]]

Brighter image:
[[ 56 171 241 155  26  89 118  47]
 [ 35 196 108 180   0  22  97 209]
 [ 94 163 159 150  98 167 163  23]
 [ 23  81  87 121 170 133 158 190]
 [173 218  86  18 185  51 189 123]
 [  2  22  15 220  87 120 244 100]
 [166 100 153 210  42 152 114 202]
 [181 234  37 143 153   8 186  25]]

Reduced contrast:
[[195 252 159 244 180 211 226 190]
 [184 137 221 129 167 178 215 143]
 [214 248 246 242 216 250 248 178]
 [178 207 210 227 252 233 246 134]
 [253 148 210 176 131 192 133 228]
 [168 178 174 149 210 227 161 217]
 [250 217 243 144 188 243 224 140]
 [129 156 185 238 243 171 132 179]]

Inverted:
[[249 134  64 150  23 216 187   2]
 [ 14 109 197 125  49  27 208  96]
 [211 142 1

In [85]:
# Example 2: Financial Analysis (stock portfolio)

# Stock data: [price, shares owned]
stocks = np.array([
    [150.5, 10],   # Stock A
    [75.25, 20],   # Stock B
    [200.0, 5],    # Stock C
    [50.75, 30],   # Stock D
    [125.5, 15]    # Stock E
])

prices = stocks[:, 0]
shares = stocks[:, 1]

print("Portfolio:")
for i, (price, share) in enumerate(stocks):
    print(f"Stock {chr(65+i)}: ${price:.2f} × {share:.0f} shares")

# Calculate total value per stock
values = prices * shares
print(f"\nValue per stock: {values}")

# Total portfolio value
total_value = np.sum(values)
print(f"Total portfolio value: ${total_value:,.2f}")

# Portfolio weights (percentage of total)
weights = (values / total_value) * 100
print("\nPortfolio allocation:")
for i, weight in enumerate(weights):
    print(f"Stock {chr(65+i)}: {weight:.1f}%")

# Simulate price changes
price_changes = np.array([0.05, -0.02, 0.03, -0.01, 0.04])
new_prices = prices * (1 + price_changes)
new_values = new_prices * shares
profit = np.sum(new_values) - total_value

print(f"\nAfter price changes:")
print(f"New total value: ${np.sum(new_values):,.2f}")
print(f"Profit/Loss: ${profit:,.2f} ({(profit/total_value)*100:.2f}%)")

print("\n💡 NumPy handles financial calculations efficiently!")

Portfolio:
Stock A: $150.50 × 10 shares
Stock B: $75.25 × 20 shares
Stock C: $200.00 × 5 shares
Stock D: $50.75 × 30 shares
Stock E: $125.50 × 15 shares

Value per stock: [1505.  1505.  1000.  1522.5 1882.5]
Total portfolio value: $7,415.00

Portfolio allocation:
Stock A: 20.3%
Stock B: 20.3%
Stock C: 13.5%
Stock D: 20.5%
Stock E: 25.4%

After price changes:
New total value: $7,550.23
Profit/Loss: $135.23 (1.82%)

💡 NumPy handles financial calculations efficiently!


In [86]:
# Example 3: Data Normalization (Machine Learning preprocessing)

# Simulate dataset with different scales
data = np.array([
    [25, 50000, 3],      # Age, Salary, Years Experience
    [35, 75000, 8],
    [45, 90000, 15],
    [22, 45000, 1],
    [50, 120000, 20],
    [28, 55000, 4]
])

print("Original data (Age, Salary, Experience):")
print(data)

# Min-Max Normalization (scale to 0-1)
min_vals = data.min(axis=0)
max_vals = data.max(axis=0)
normalized = (data - min_vals) / (max_vals - min_vals)

print("\nMin-Max Normalized (0 to 1):")
print(normalized.round(3))

# Z-Score Normalization (mean=0, std=1)
mean = data.mean(axis=0)
std = data.std(axis=0)
standardized = (data - mean) / std

print("\nZ-Score Standardized (mean=0, std=1):")
print(standardized.round(3))

# Verify standardization
print(f"\nStandardized mean: {standardized.mean(axis=0).round(10)}")
print(f"Standardized std: {standardized.std(axis=0).round(3)}")

print("\n💡 Normalization makes features comparable for ML algorithms!")

Original data (Age, Salary, Experience):
[[    25  50000      3]
 [    35  75000      8]
 [    45  90000     15]
 [    22  45000      1]
 [    50 120000     20]
 [    28  55000      4]]

Min-Max Normalized (0 to 1):
[[0.107 0.067 0.105]
 [0.464 0.4   0.368]
 [0.821 0.6   0.737]
 [0.    0.    0.   ]
 [1.    1.    1.   ]
 [0.214 0.133 0.158]]

Z-Score Standardized (mean=0, std=1):
[[-0.888 -0.857 -0.803]
 [ 0.081  0.095 -0.073]
 [ 1.05   0.666  0.949]
 [-1.179 -1.047 -1.095]
 [ 1.534  1.809  1.679]
 [-0.598 -0.666 -0.657]]

Standardized mean: [ 0. -0.  0.]
Standardized std: [1. 1. 1.]

💡 Normalization makes features comparable for ML algorithms!


In [87]:
# Example 4: Moving Average (Time Series Analysis)

# Simulate stock prices over 20 days
np.random.seed(42)
prices = 100 + np.cumsum(np.random.randn(20) * 2)

print("Daily stock prices:")
print(prices.round(2))

# Simple Moving Average (SMA) - 5 day window
window = 5
sma = np.convolve(prices, np.ones(window)/window, mode='valid')

print(f"\n{window}-day Simple Moving Average:")
print(sma.round(2))

# Exponential Moving Average (EMA)
alpha = 0.3
ema = np.zeros(len(prices))
ema[0] = prices[0]
for i in range(1, len(prices)):
    ema[i] = alpha * prices[i] + (1 - alpha) * ema[i-1]

print(f"\nExponential Moving Average (alpha={alpha}):")
print(ema.round(2))

# Detect trend
price_change = np.diff(prices)
uptrend_days = np.sum(price_change > 0)
downtrend_days = np.sum(price_change < 0)

print(f"\nTrend analysis:")
print(f"Up days: {uptrend_days}, Down days: {downtrend_days}")
print(f"Overall change: ${prices[-1] - prices[0]:.2f}")

print("\n💡 Moving averages smooth out noise in time series data!")

Daily stock prices:
[100.99 100.72 102.01 105.06 104.59 104.12 107.28 108.82 107.88 108.96
 108.03 107.1  107.59 103.76 100.31  99.19  97.16  97.79  95.97  93.15]

5-day Simple Moving Average:
[102.67 103.3  104.61 105.97 106.54 107.41 108.19 108.16 107.91 107.09
 105.36 103.59 101.6   99.64  98.08  96.65]

Exponential Moving Average (alpha=0.3):
[100.99 100.91 101.24 102.39 103.05 103.37 104.54 105.82 106.44 107.2
 107.45 107.34 107.42 106.32 104.52 102.92 101.19 100.17  98.91  97.18]

Trend analysis:
Up days: 7, Down days: 12
Overall change: $-7.85

💡 Moving averages smooth out noise in time series data!


In [88]:
# Example 5: Distance Calculations (Clustering/Nearest Neighbors)

# Points in 2D space
points = np.array([
    [1, 2],
    [4, 6],
    [2, 3],
    [8, 8],
    [5, 5]
])

print("Points (x, y):")
for i, point in enumerate(points):
    print(f"Point {i}: {point}")

# Calculate distances from point 0 to all others
point_0 = points[0]
differences = points - point_0
distances = np.sqrt(np.sum(differences**2, axis=1))

print(f"\nDistances from Point 0 {point_0}:")
for i, dist in enumerate(distances):
    print(f"To Point {i}: {dist:.2f}")

# Find nearest neighbor
nearest_idx = np.argsort(distances)[1]  # Skip 0 (itself)
print(f"\nNearest neighbor to Point 0: Point {nearest_idx} at {points[nearest_idx]}")

# Pairwise distance matrix
n = len(points)
dist_matrix = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        dist_matrix[i, j] = np.linalg.norm(points[i] - points[j])

print("\nPairwise distance matrix:")
print(dist_matrix.round(2))

# Vectorized version (much faster!)
diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
dist_matrix_fast = np.sqrt(np.sum(diff**2, axis=2))
print("\nVectorized distance matrix:")
print(dist_matrix_fast.round(2))

print("\n💡 NumPy makes geometric calculations efficient!")

Points (x, y):
Point 0: [1 2]
Point 1: [4 6]
Point 2: [2 3]
Point 3: [8 8]
Point 4: [5 5]

Distances from Point 0 [1 2]:
To Point 0: 0.00
To Point 1: 5.00
To Point 2: 1.41
To Point 3: 9.22
To Point 4: 5.00

Nearest neighbor to Point 0: Point 2 at [2 3]

Pairwise distance matrix:
[[0.   5.   1.41 9.22 5.  ]
 [5.   0.   3.61 4.47 1.41]
 [1.41 3.61 0.   7.81 3.61]
 [9.22 4.47 7.81 0.   4.24]
 [5.   1.41 3.61 4.24 0.  ]]

Vectorized distance matrix:
[[0.   5.   1.41 9.22 5.  ]
 [5.   0.   3.61 4.47 1.41]
 [1.41 3.61 0.   7.81 3.61]
 [9.22 4.47 7.81 0.   4.24]
 [5.   1.41 3.61 4.24 0.  ]]

💡 NumPy makes geometric calculations efficient!


In [89]:
# Example 6: Monte Carlo Simulation (Estimating π)

# Throw random darts at a square, count how many land in inscribed circle
n_samples = 100000

# Random points in [0,1] x [0,1]
x = np.random.rand(n_samples)
y = np.random.rand(n_samples)

# Distance from origin
distances = np.sqrt(x**2 + y**2)

# Count points inside unit circle (distance < 1)
inside_circle = np.sum(distances < 1)

# Estimate π: (points in circle / total points) = (π/4) / 1
pi_estimate = 4 * inside_circle / n_samples

print(f"Monte Carlo Simulation with {n_samples:,} samples:")
print(f"Points inside circle: {inside_circle:,}")
print(f"Points outside circle: {n_samples - inside_circle:,}")
print(f"\nEstimated π: {pi_estimate:.6f}")
print(f"Actual π: {np.pi:.6f}")
print(f"Error: {abs(pi_estimate - np.pi):.6f}")

# Show convergence with different sample sizes
sample_sizes = [100, 1000, 10000, 100000]
print("\nConvergence:")
for n in sample_sizes:
    x = np.random.rand(n)
    y = np.random.rand(n)
    inside = np.sum(np.sqrt(x**2 + y**2) < 1)
    estimate = 4 * inside / n
    error = abs(estimate - np.pi)
    print(f"n={n:6d}: π≈{estimate:.6f}, error={error:.6f}")

print("\n💡 More samples = better estimate!")

Monte Carlo Simulation with 100,000 samples:
Points inside circle: 78,439
Points outside circle: 21,561

Estimated π: 3.137560
Actual π: 3.141593
Error: 0.004033

Convergence:
n=   100: π≈3.040000, error=0.101593
n=  1000: π≈3.252000, error=0.110407
n= 10000: π≈3.134800, error=0.006793
n=100000: π≈3.139480, error=0.002113

💡 More samples = better estimate!


---
# 🎉 Congratulations!

You've completed the comprehensive NumPy tutorial! You now know:

✅ **Basics**: Array creation, properties, data types  
✅ **Indexing**: Slicing, boolean indexing, fancy indexing  
✅ **Reshaping**: reshape, transpose, flatten, stack  
✅ **Operations**: Element-wise, broadcasting, aggregations  
✅ **Broadcasting**: Smart operations on different shapes  
✅ **Linear Algebra**: Matrix operations, solving equations  
✅ **Random**: Generating random data and distributions  
✅ **Sorting**: Sorting, searching, argsort  
✅ **Advanced Indexing**: where, select, choose  
✅ **Manipulation**: Concatenate, split, stack, repeat  
✅ **Set Operations**: Unique, union, intersection  
✅ **File I/O**: Saving and loading arrays  
✅ **Ufuncs**: Fast universal functions  
✅ **Statistics**: Percentiles, correlation, histograms  
✅ **Polynomials**: Fitting, derivatives, integration  
✅ **Structured Arrays**: Named fields and records  
✅ **Performance**: Views vs copies, vectorization  
✅ **Real-World**: Practical applications

## Next Steps:

1. **Practice**: Try the examples with your own data
2. **Explore**: Check out pandas (built on NumPy) for data analysis
3. **Learn**: Study scikit-learn for machine learning
4. **Build**: Create projects using NumPy

## Resources:

- Official docs: https://numpy.org/doc/
- NumPy tutorials: https://numpy.org/learn/
- Practice problems: https://www.w3resource.com/python-exercises/numpy/

**Happy coding! 🚀**